from __future__ import annotations

import argparse
import json
import sys
import textwrap


REGISTRY_STATUS = [
    "PROTECTED_ACTION_REGISTRY",
    "LOCAL_ONLY",
    "STRICT_ACTION_ALLOWLIST",
    "CANONICALIZE_BEFORE_VALIDATE",
    "ACTION_SPECIFIC_CONTRACTS_STILL_REQUIRED",
    "AUTHORITY_HIERARCHY_STILL_REQUIRED",
    "GUARDS_STILL_REQUIRED",
    "BLOCKED_ACTIONS_REMAIN_BLOCKED",
    "NO_ACTION_EXECUTION",
    "NO_PROVIDER_CALLS",
    "NO_NETWORK",
    "NO_BROWSER",
    "NO_MODEL_RUNTIME",
    "NO_BACKGROUND_WORKER",
    "NO_STARTUP_AUTORUN",
]

REQUIRED_ACTION_FIELDS = [
    "action_id",
    "display_name",
    "category",
    "risk_level",
    "password_required",
    "approval_token_required",
    "contract_required",
    "verifier_required",
    "receipt_required",
    "dry_run_required_first",
    "allowed_in_gui",
    "allowed_in_cli",
    "current_state",
    "blocked_reason",
    "required_contracts",
    "required_verifiers",
    "required_receipt_folder",
    "safety_boundary",
    "forbidden_without_extra_approval",
    "notes",
]

RISK_LEVELS = ["view_only", "low", "medium", "high", "blocked"]

DEFAULT_GUARD_VERIFIERS = [
    "tools\\verify_untrusted_content_guard.py",
    "tools\\verify_prompt_injection_guard.py",
    "tools\\verify_authority_hierarchy.py",
]


def _action(
    action_id: str,
    display_name: str,
    category: str,
    risk_level: str,
    *,
    password_required: bool,
    approval_token_required: bool = False,
    contract_required: bool = False,
    verifier_required: bool = False,
    receipt_required: bool = False,
    dry_run_required_first: bool = False,
    allowed_in_gui: bool = False,
    allowed_in_cli: bool = True,
    current_state: str = "available_with_gate",
    blocked_reason: str = "",
    required_contracts: list[str] | None = None,
    required_verifiers: list[str] | None = None,
    required_receipt_folder: str = "",
    safety_boundary: str = "",
    forbidden_without_extra_approval: list[str] | None = None,
    notes: str = "",
) -> dict[str, object]:
    if risk_level not in RISK_LEVELS:
        raise ValueError("unknown risk level for protected action registry")
    return {
        "action_id": action_id,
        "display_name": display_name,
        "category": category,
        "risk_level": risk_level,
        "password_required": password_required,
        "approval_token_required": approval_token_required,
        "contract_required": contract_required,
        "verifier_required": verifier_required,
        "receipt_required": receipt_required,
        "dry_run_required_first": dry_run_required_first,
        "allowed_in_gui": allowed_in_gui,
        "allowed_in_cli": allowed_in_cli,
        "current_state": current_state,
        "blocked_reason": blocked_reason,
        "required_contracts": required_contracts or [],
        "required_verifiers": required_verifiers or [],
        "required_receipt_folder": required_receipt_folder,
        "safety_boundary": safety_boundary,
        "forbidden_without_extra_approval": forbidden_without_extra_approval or [],
        "notes": notes,
    }


BLOCKED_REQUIRES_FUTURE_CONTRACT = "blocked_until_separate_future_contract"

PROTECTED_ACTIONS: list[dict[str, object]] = [
    _action(
        "run_bounded_self_learning_scheduler",
        "Run bounded self-learning scheduler",
        "Engel AI / Learning",
        "medium",
        password_required=True,
        contract_required=True,
        verifier_required=True,
        receipt_required=True,
        allowed_in_cli=True,
        required_contracts=["Engel Bounded Self-Learning Scheduler V1"],
        required_verifiers=["tools\\verify_engel_bounded_self_learning_scheduler.py", *DEFAULT_GUARD_VERIFIERS],
        required_receipt_folder="reports\\self_learning_scheduler_receipts",
        safety_boundary="Foreground explicit job list only; candidate outputs only.",
        notes="Write-candidates mode must be password-gated and remains candidate-only.",
    ),
    _action(
        "run_daily_cycle",
        "Run daily cycle",
        "Engel AI / Learning",
        "medium",
        password_required=True,
        contract_required=True,
        verifier_required=True,
        receipt_required=True,
        allowed_in_cli=True,
        required_contracts=["Engel Daily Cycle Runner V1"],
        required_verifiers=["tools\\verify_engel_daily_cycle_runner.py", *DEFAULT_GUARD_VERIFIERS],
        required_receipt_folder="reports\\daily_cycle_receipts",
        safety_boundary="One foreground bounded cycle per invocation.",
        notes="Dry-run may remain available without password; run mode requires a password prompt.",
    ),
    _action(
        "run_daily_cycle_with_learning_jobs",
        "Run daily cycle with learning jobs",
        "Engel AI / Learning",
        "high",
        password_required=True,
        approval_token_required=True,
        contract_required=True,
        verifier_required=True,
        receipt_required=True,
        dry_run_required_first=True,
        allowed_in_cli=True,
        required_contracts=["Engel Daily Cycle Runner V1", "Engel Bounded Self-Learning Scheduler V1"],
        required_verifiers=["tools\\verify_engel_daily_cycle_runner.py", "tools\\verify_engel_bounded_self_learning_scheduler.py", *DEFAULT_GUARD_VERIFIERS],
        required_receipt_folder="reports\\daily_cycle_receipts",
        safety_boundary="Learning jobs stay candidate-only and foreground bounded.",
        forbidden_without_extra_approval=["unbounded jobs", "trusted-memory write", "background worker"],
        notes="Password is necessary, not sufficient; explicit approval and verifier compatibility still apply.",
    ),
    _action(
        "create_learning_job_draft",
        "Create learning job draft",
        "Engel AI / Learning",
        "view_only",
        password_required=False,
        contract_required=True,
        verifier_required=True,
        allowed_in_cli=True,
        current_state="available_stdout_only",
        required_contracts=["memory\\ENGEL_LEARNING_JOB_QUEUE_CONTRACT_V1.md"],
        required_verifiers=["tools\\verify_engel_learning_job_queue.py"],
        safety_boundary="Drafts one explicit real-source learning job JSON to stdout only; no queue write, fake approval, or learning run.",
        notes="The source file must exist and must be project-local or approved-library-local.",
    ),
    _action(
        "write_learning_job_draft",
        "Write learning job draft",
        "Engel AI / Learning",
        "low",
        password_required=True,
        contract_required=True,
        verifier_required=True,
        receipt_required=True,
        allowed_in_cli=True,
        current_state="available_protected_write",
        required_contracts=["memory\\ENGEL_LEARNING_JOB_QUEUE_CONTRACT_V1.md"],
        required_verifiers=["tools\\verify_engel_learning_job_queue.py", *DEFAULT_GUARD_VERIFIERS],
        required_receipt_folder="reports\\learning_job_queue_receipts",
        safety_boundary="Writes queue metadata only from an explicit real source; no fake queue record, fake approval, learning job run, trusted-memory write, source mutation, patch apply, provider/network/browser call, Android connection, or model runtime.",
        forbidden_without_extra_approval=["fake approval", "learning job run", "trusted-memory write", "source mutation", "patch apply", "model runtime"],
        notes="Use --password-prompt; password is never accepted as a CLI argument.",
    ),
    _action(
        "queue_learning_job",
        "Queue learning job",
        "Engel AI / Learning",
        "medium",
        password_required=True,
        contract_required=True,
        verifier_required=True,
        receipt_required=True,
        allowed_in_cli=True,
        current_state="available_protected_queue_metadata_only",
        required_contracts=["memory\\ENGEL_LEARNING_JOB_QUEUE_CONTRACT_V1.md"],
        required_verifiers=["tools\\verify_engel_learning_job_queue.py", *DEFAULT_GUARD_VERIFIERS],
        required_receipt_folder="reports\\learning_job_queue_receipts",
        safety_boundary="Marks an explicit validated real-source job as queued metadata only; it does not run learning or create fake approval.",
        forbidden_without_extra_approval=["fake approval", "learning job run", "trusted-memory write", "source mutation", "patch apply", "background worker"],
        notes="The future Self-Learning Run Controller owns execution; this action only queues metadata.",
    ),
    _action(
        "validate_learning_job",
        "Validate learning job",
        "Engel AI / Learning",
        "view_only",
        password_required=False,
        contract_required=True,
        verifier_required=True,
        allowed_in_cli=True,
        current_state="available_view_only",
        required_contracts=["memory\\ENGEL_LEARNING_JOB_QUEUE_CONTRACT_V1.md"],
        required_verifiers=["tools\\verify_engel_learning_job_queue.py"],
        safety_boundary="Validates one explicit project-local job JSON; no queue write or learning run.",
        notes="Rejects model files, WSL distro/tar sources, URLs, live/staging artifacts, and trusted-memory paths.",
    ),
    _action(
        "list_learning_jobs",
        "List learning jobs",
        "Engel AI / Learning",
        "view_only",
        password_required=False,
        contract_required=True,
        verifier_required=True,
        allowed_in_cli=True,
        current_state="available_view_only",
        required_contracts=["memory\\ENGEL_LEARNING_JOB_QUEUE_CONTRACT_V1.md"],
        required_verifiers=["tools\\verify_engel_learning_job_queue.py"],
        safety_boundary="Lists queue files non-recursively; no queue write or learning run.",
        notes="Queue folder is reports\\learning_job_queue.",
    ),
    _action(
        "self_upgrade_create_issue",
        "Create self-upgrade issue",
        "Engel AI / Self-Upgrade",
        "low",
        password_required=False,
        contract_required=True,
        verifier_required=True,
        receipt_required=True,
        allowed_in_cli=True,
        current_state="available_report_write",
        required_contracts=["memory\\ENGEL_SELF_UPGRADE_SYSTEM_CONTRACT_V1.md"],
        required_verifiers=["tools\\verify_engel_self_upgrade_system.py", *DEFAULT_GUARD_VERIFIERS],
        required_receipt_folder="reports\\self_upgrade\\issues",
        safety_boundary="Writes one issue ledger record only; no route mutation, source mutation, trusted-memory write, provider call, model run, storage mutation, or worker control.",
        notes="Issue records are evidence, not fixes.",
    ),
    _action(
        "self_upgrade_route_issue",
        "Route self-upgrade issue",
        "Engel AI / Self-Upgrade",
        "low",
        password_required=False,
        contract_required=True,
        verifier_required=True,
        receipt_required=True,
        allowed_in_cli=True,
        current_state="available_report_write",
        required_contracts=["memory\\ENGEL_SELF_UPGRADE_SYSTEM_CONTRACT_V1.md", "memory\\ENGEL_SELF_UPGRADE_VERIFIER_MATRIX_V1.json"],
        required_verifiers=["tools\\verify_engel_self_upgrade_system.py", *DEFAULT_GUARD_VERIFIERS],
        required_receipt_folder="reports\\self_upgrade\\routes",
        safety_boundary="Writes one route packet only; does not dispatch unsafe work, mutate live routes, call providers, start workers, or apply code.",
        notes="Route packets keep Sub desktop and Android workers bounded by their existing gates.",
    ),
    _action(
        "self_upgrade_create_patch_candidate",
        "Create self-upgrade patch candidate",
        "Engel AI / Self-Upgrade",
        "medium",
        password_required=True,
        contract_required=True,
        verifier_required=True,
        receipt_required=True,
        allowed_in_cli=True,
        current_state="available_protected_candidate_write",
        required_contracts=["memory\\ENGEL_SELF_UPGRADE_SYSTEM_CONTRACT_V1.md"],
        required_verifiers=["tools\\verify_engel_self_upgrade_system.py", "tools\\verify_engel_fix_candidate_queue.py", *DEFAULT_GUARD_VERIFIERS],
        required_receipt_folder="reports\\self_upgrade\\patch_candidates",
        safety_boundary="Writes one candidate bundle only; no patch apply, no source mutation, no trusted-memory write, no provider call, no storage mutation.",
        forbidden_without_extra_approval=["source mutation", "trusted-memory write", "route authority mutation", "provider key/session change", "storage mutation"],
        notes="Candidate bundles must include risk, rollback plan, verifier list, and engel-hdd-vault archive context.",
    ),
    _action(
        "self_upgrade_gate_candidate",
        "Gate self-upgrade patch candidate",
        "Engel AI / Self-Upgrade",
        "high",
        password_required=True,
        approval_token_required=True,
        contract_required=True,
        verifier_required=True,
        receipt_required=True,
        dry_run_required_first=True,
        allowed_in_cli=True,
        current_state="available_gate_receipt_only",
        required_contracts=["memory\\ENGEL_SELF_UPGRADE_SYSTEM_CONTRACT_V1.md"],
        required_verifiers=["tools\\verify_engel_self_upgrade_system.py", "tools\\verify_engel_code_companion_protected_patch_apply.py", *DEFAULT_GUARD_VERIFIERS],
        required_receipt_folder="reports\\self_upgrade\\gate_receipts",
        safety_boundary="Gate receipt only; medium/high risk remains blocked from apply until Josh approval and verifier evidence exist.",
        forbidden_without_extra_approval=["apply patch", "source mutation", "trusted-memory write", "Sub desktop shell/disk", "storage mutation", "startup service mutation"],
        notes="V1 does not silently apply patches.",
    ),
    _action(
        "self_upgrade_apply_candidate",
        "Apply approved low-risk self-upgrade candidate",
        "Engel AI / Self-Upgrade",
        "high",
        password_required=True,
        approval_token_required=True,
        contract_required=True,
        verifier_required=True,
        receipt_required=True,
        dry_run_required_first=True,
        allowed_in_cli=True,
        current_state="available_low_risk_apply_only",
        required_contracts=["memory\\ENGEL_SELF_UPGRADE_SYSTEM_CONTRACT_V1.md"],
        required_verifiers=["tools\\verify_engel_self_upgrade_system.py", "tools\\verify_engel_code_companion_protected_patch_apply.py", *DEFAULT_GUARD_VERIFIERS],
        required_receipt_folder="reports\\self_upgrade\\apply_receipts",
        safety_boundary="Applies only an approved low-risk exact-text JSON patch after a gate receipt allows apply; writes rollback snapshot and apply receipt; no provider direct apply or trusted-memory write.",
        forbidden_without_extra_approval=["medium/high-risk patch", "trusted-memory write", "route authority mutation", "provider key/session change", "storage mutation", "startup service mutation", "Sub desktop shell/disk"],
        notes="Requires APPROVE_ENGEL_SELF_UPGRADE_LOW_RISK_V1 at gate time and APPLY_ENGEL_SELF_UPGRADE_LOW_RISK_V1 at apply time.",
    ),
    _action(
        "self_upgrade_memory_candidate",
        "Create self-upgrade memory candidate",
        "Engel AI / Self-Upgrade",
        "medium",
        password_required=True,
        contract_required=True,
        verifier_required=True,
        receipt_required=True,
        allowed_in_cli=True,
        current_state="available_candidate_memory_write",
        required_contracts=["memory\\ENGEL_SELF_UPGRADE_SYSTEM_CONTRACT_V1.md"],
        required_verifiers=["tools\\verify_engel_self_upgrade_system.py", "tools\\verify_engel_approved_memory_promotion.py", *DEFAULT_GUARD_VERIFIERS],
        required_receipt_folder="reports\\self_upgrade\\memory_candidates",
        safety_boundary="Writes candidate memory only; no trusted-memory promotion or prompt injection into runtime context.",
        forbidden_without_extra_approval=["trusted-memory write", "approved memory promotion", "routing memory injection"],
        notes="Trusted memory remains a separate human-approved promotion path.",
    ),
    _action(
        "self_learning_run_controller_status",
        "View self-learning run controller status",
        "Engel AI / Learning",
        "view_only",
        password_required=False,
        contract_required=True,
        verifier_required=True,
        allowed_in_cli=True,
        current_state="available_view_only",
        required_contracts=["memory\\ENGEL_SELF_LEARNING_RUN_CONTROLLER_CONTRACT_V1.md"],
        required_verifiers=["tools\\verify_engel_self_learning_run_controller.py"],
        safety_boundary="Displays controller folders, limits, and candidate-only boundaries; no learning run or output write.",
        notes="Status mode is read-only.",
    ),
    _action(
        "self_learning_run_controller_dry_run",
        "Dry-run self-learning run controller",
        "Engel AI / Learning",
        "view_only",
        password_required=False,
        contract_required=True,
        verifier_required=True,
        allowed_in_cli=True,
        current_state="available_view_only",
        required_contracts=["memory\\ENGEL_SELF_LEARNING_RUN_CONTROLLER_CONTRACT_V1.md"],
        required_verifiers=["tools\\verify_engel_self_learning_run_controller.py", "tools\\verify_engel_learning_job_queue.py"],
        safety_boundary="Validates one explicit Learning Job Queue job and reports the candidate-only pipeline; no outputs are created.",
        notes="Dry-run does not require a password because it does not write or run the pipeline.",
    ),
    _action(
        "self_learning_run_controller_run_once",
        "Run one self-learning controller job",
        "Engel AI / Learning",
        "medium",
        password_required=True,
        contract_required=True,
        verifier_required=True,
        receipt_required=True,
        dry_run_required_first=True,
        allowed_in_cli=True,
        current_state="available_password_gated_one_job_only",
        required_contracts=["memory\\ENGEL_SELF_LEARNING_RUN_CONTROLLER_CONTRACT_V1.md", "memory\\ENGEL_LEARNING_JOB_QUEUE_CONTRACT_V1.md"],
        required_verifiers=["tools\\verify_engel_self_learning_run_controller.py", "tools\\verify_engel_learning_job_queue.py", *DEFAULT_GUARD_VERIFIERS],
        required_receipt_folder="reports\\self_learning_run_receipts",
        safety_boundary="Runs one explicit queued real-source learning job and creates untrusted candidate outputs only; no trusted-memory write, source mutation, patch apply, model runtime, WSL/Hermes/Android runtime, provider/network/browser call, background worker, or startup autorun.",
        forbidden_without_extra_approval=["trusted-memory write", "source mutation", "patch apply", "model runtime", "background worker", "startup autorun"],
        notes="Password is required and not sufficient; outputs require human review before any trusted action.",
    ),
    _action(
        "self_learning_run_controller_list_receipts",
        "List self-learning run controller receipts",
        "Engel AI / Learning",
        "view_only",
        password_required=False,
        contract_required=True,
        verifier_required=True,
        allowed_in_cli=True,
        current_state="available_view_only",
        required_contracts=["memory\\ENGEL_SELF_LEARNING_RUN_CONTROLLER_CONTRACT_V1.md"],
        required_verifiers=["tools\\verify_engel_self_learning_run_controller.py"],
        safety_boundary="Lists self-learning run receipts non-recursively; no run or write.",
        notes="Receipt folder is reports\\self_learning_run_receipts.",
    ),
    _action(
        "enable_research_toggle_overnight_worker",
        "Enable Research toggle overnight worker",
        "Engel AI / Learning",
        "medium",
        password_required=False,
        contract_required=True,
        verifier_required=True,
        allowed_in_gui=True,
        allowed_in_cli=True,
        required_contracts=["Engel Research Toggle Overnight Worker Contract V1", "Engel Background Worker and Startup Autorun Contract V1"],
        required_verifiers=["tools\\verify_engel_research_toggle_overnight_worker.py", *DEFAULT_GUARD_VERIFIERS],
        safety_boundary="Enables bounded candidate-only worker mode only; does not start a loop.",
        notes="No password prompt required; startup autorun remains disabled.",
    ),
    _action(
        "disable_research_toggle_overnight_worker",
        "Disable Research toggle overnight worker",
        "Engel AI / Learning",
        "low",
        password_required=False,
        contract_required=True,
        verifier_required=True,
        allowed_in_gui=True,
        allowed_in_cli=True,
        required_contracts=["Engel Research Toggle Overnight Worker Contract V1"],
        required_verifiers=["tools\\verify_engel_research_toggle_overnight_worker.py", *DEFAULT_GUARD_VERIFIERS],
        safety_boundary="Disables bounded worker mode metadata only.",
        notes="No password prompt required. No broad process termination is authorized.",
    ),
    _action(
        "run_research_toggle_worker_dry_run",
        "Run Research toggle worker dry-run",
        "Engel AI / Learning",
        "low",
        password_required=False,
        contract_required=True,
        verifier_required=True,
        allowed_in_cli=True,
        required_contracts=["Engel Research Toggle Overnight Worker Contract V1"],
        required_verifiers=["tools\\verify_engel_research_toggle_overnight_worker.py", *DEFAULT_GUARD_VERIFIERS],
        safety_boundary="Validates explicit project-local JSON jobs and limits; no candidate writes.",
        notes="Dry-run is non-mutating and does not require password.",
    ),
    _action(
        "run_research_toggle_worker_once",
        "Run Research toggle worker once",
        "Engel AI / Learning",
        "medium",
        password_required=False,
        contract_required=True,
        verifier_required=True,
        receipt_required=True,
        dry_run_required_first=True,
        allowed_in_cli=True,
        required_contracts=["Engel Research Toggle Overnight Worker Contract V1", "Engel Background Worker and Startup Autorun Contract V1"],
        required_verifiers=["tools\\verify_engel_research_toggle_overnight_worker.py", *DEFAULT_GUARD_VERIFIERS],
        required_receipt_folder="reports\\overnight_research_receipts",
        safety_boundary="Runs one bounded candidate-only batch from an explicit job list.",
        notes="Requires worker mode enabled first; no password prompt and no startup autorun.",
    ),
    _action(
        "run_research_toggle_worker_overnight",
        "Run Research toggle worker overnight",
        "Engel AI / Learning",
        "medium",
        password_required=False,
        contract_required=True,
        verifier_required=True,
        receipt_required=True,
        dry_run_required_first=True,
        allowed_in_cli=True,
        required_contracts=["Engel Research Toggle Overnight Worker Contract V1", "Engel Background Worker and Startup Autorun Contract V1"],
        required_verifiers=["tools\\verify_engel_research_toggle_overnight_worker.py", *DEFAULT_GUARD_VERIFIERS],
        required_receipt_folder="reports\\overnight_research_receipts",
        safety_boundary="Runs bounded overnight candidate-only jobs with max runtime and max jobs.",
        notes="No password prompt, no endless loop, and no startup autorun install.",
    ),
    _action(
        "research_toggle_worker_kill_switch",
        "Research toggle worker kill switch",
        "Engel AI / Learning",
        "low",
        password_required=False,
        contract_required=True,
        verifier_required=True,
        allowed_in_gui=True,
        allowed_in_cli=True,
        required_contracts=["Engel Research Toggle Overnight Worker Contract V1"],
        required_verifiers=["tools\\verify_engel_research_toggle_overnight_worker.py", *DEFAULT_GUARD_VERIFIERS],
        safety_boundary="Trips bounded worker metadata kill switch and disables worker mode.",
        notes="No password prompt required. No broad process sweep is authorized.",
    ),
    _action(
        "generate_research_note_write",
        "Generate research note write",
        "Engel AI / Learning",
        "medium",
        password_required=True,
        contract_required=True,
        verifier_required=True,
        receipt_required=True,
        required_contracts=["Engel Research Note Generator V1"],
        safety_boundary="Research notes are untrusted local artifacts.",
        notes="No provider, browser, or live research activation is authorized by the registry.",
    ),
    _action(
        "extract_lesson_candidate_write",
        "Extract lesson candidate write",
        "Engel AI / Learning",
        "medium",
        password_required=True,
        contract_required=True,
        verifier_required=True,
        receipt_required=True,
        safety_boundary="Lesson candidates are not approved lessons.",
        notes="Candidate creation remains untrusted until human review.",
    ),
    _action(
        "create_memory_candidate_proposal_write",
        "Create memory candidate proposal write",
        "Engel AI / Learning",
        "medium",
        password_required=True,
        approval_token_required=True,
        contract_required=True,
        verifier_required=True,
        receipt_required=True,
        required_contracts=["Engel Memory Candidate Proposal V1"],
        required_receipt_folder="reports\\memory_candidates",
        safety_boundary="Memory proposals are not trusted memory.",
        notes="Embedded approval text in content does not count as authorization.",
    ),
    _action(
        "approved_graph_build",
        "Run approved De Bruijn graph build",
        "De Bruijn Build/Promote",
        "high",
        password_required=True,
        approval_token_required=True,
        contract_required=True,
        verifier_required=True,
        receipt_required=True,
        dry_run_required_first=True,
        allowed_in_cli=True,
        required_contracts=[
            "ENGEL_DEBRUIJN_QUANTUM_APPROVED_BUILD_COMMAND_CONTRACT_V1",
            "ENGEL_DEBRUIJN_QUANTUM_APPROVED_BUILD_LANE_CONTRACT_V1",
            "ENGEL_DEBRUIJN_QUANTUM_APPROVED_BUILD_SCRIPT_ALLOWLIST_CONTRACT_V1",
        ],
        required_verifiers=[
            "tools\\verify_debruijn_quantum_approved_build_command.py",
            "tools\\verify_debruijn_quantum_approved_build_lane.py",
            "tools\\verify_debruijn_quantum_approved_build_script_allowlist_contract.py",
            "tools\\verify_engel_global_password_gate.py",
        ],
        required_receipt_folder="reports\\debruijn_quantum_build_receipts",
        safety_boundary="Exact approval phrase, password gate, graph candidate validation, fixed build script allowlist, timeout classification, and receipt required. No promote or live write.",
        forbidden_without_extra_approval=["live write", "dist write", "backup write", "promote", "trusted memory write", "provider/network/model call"],
        notes="Runs only approved graph build scripts under build\\staging after all gates pass.",
    ),
    _action(
        "approved_graph_promote",
        "Run approved De Bruijn graph promote",
        "De Bruijn Build/Promote",
        "high",
        password_required=True,
        approval_token_required=True,
        contract_required=True,
        verifier_required=True,
        receipt_required=True,
        dry_run_required_first=True,
        allowed_in_cli=True,
        required_contracts=[
            "ENGEL_DEBRUIJN_QUANTUM_APPROVED_PROMOTE_COMMAND_CONTRACT_V1",
            "ENGEL_DEBRUIJN_QUANTUM_APPROVED_PROMOTE_LANE_CONTRACT_V1",
        ],
        required_verifiers=[
            "tools\\verify_debruijn_quantum_approved_promote_command.py",
            "tools\\verify_debruijn_quantum_approved_promote_lane.py",
            "tools\\verify_engel_global_password_gate.py",
        ],
        required_receipt_folder="reports\\debruijn_quantum_promote_receipts",
        safety_boundary="Exact approval phrase, password gate, build receipt validation, staged artifact validation, backup/live target gates, and receipt required.",
        forbidden_without_extra_approval=["unverified staged artifact", "missing backup plan", "trusted memory write", "provider/network/model call"],
        notes="Registered for password gating; actual promote remains controlled by the promote lane implementation.",
    ),
    _action(
        "promote_memory_candidate",
        "Promote memory candidate",
        "Memory Promotion",
        "high",
        password_required=True,
        approval_token_required=True,
        contract_required=True,
        verifier_required=True,
        receipt_required=True,
        dry_run_required_first=True,
        allowed_in_cli=True,
        required_contracts=["Engel Approved Memory Promotion Contract V1"],
        required_verifiers=["tools\\verify_engel_memory_promotion_writer.py", *DEFAULT_GUARD_VERIFIERS],
        required_receipt_folder="reports\\memory_promotion_receipts",
        safety_boundary="Approval token, password, guard checks, and clear trusted-memory target are all required.",
        forbidden_without_extra_approval=["trusted memory target change", "guard bypass", "authority bypass"],
        notes="The existing writer still stops when the trusted-memory target is unclear.",
    ),
    _action(
        "enable_trusted_memory_target",
        "Enable trusted-memory target",
        "Memory Promotion",
        "high",
        password_required=True,
        approval_token_required=True,
        contract_required=True,
        verifier_required=True,
        receipt_required=True,
        dry_run_required_first=False,
        allowed_in_cli=True,
        required_contracts=["ENGEL_TRUSTED_MEMORY_TARGET_ENABLE_CONTRACT_V1"],
        required_verifiers=[
            "tools\\verify_engel_trusted_memory_target_enable_contract.py",
            "tools\\verify_engel_trusted_memory_target.py",
            "tools\\verify_engel_global_password_gate.py",
            *DEFAULT_GUARD_VERIFIERS,
        ],
        required_receipt_folder="reports\\memory_promotion_receipts",
        safety_boundary="Enables only the explicit append-only target path; does not approve or write any memory candidate.",
        forbidden_without_extra_approval=["memory candidate promotion", "bulk import", "trusted-memory overwrite", "source/route/queue mutation"],
        notes="Requires exact APPROVE_TRUSTED_MEMORY_TARGET_ENABLE_V1 phrase and password gate; per-memory promotion remains separately gated.",
    ),
    _action(
        "change_memory_promotion_contract",
        "Change memory promotion contract",
        "Memory Promotion",
        "blocked",
        password_required=True,
        current_state="blocked",
        blocked_reason=BLOCKED_REQUIRES_FUTURE_CONTRACT,
        safety_boundary="Contract changes require a separate approved update.",
        notes="Blocked actions remain blocked even with password verification.",
    ),
    _action(
        "write_trusted_memory",
        "Write trusted memory",
        "Memory Promotion",
        "blocked",
        password_required=True,
        current_state="blocked",
        blocked_reason="trusted_memory_write_requires_separate_contract_and_target",
        safety_boundary="No direct trusted-memory write is authorized here.",
        notes="Password possession never bypasses memory promotion contracts.",
    ),
    _action(
        "run_low_risk_self_fix_dry_run",
        "Run low-risk self-fix dry-run",
        "Low-Risk Self-Fix",
        "low",
        password_required=False,
        contract_required=True,
        verifier_required=True,
        allowed_in_cli=True,
        required_contracts=["Engel Low-Risk Self-Fix Runner Contract V1"],
        required_verifiers=["tools\\verify_engel_low_risk_self_fix_runner.py", *DEFAULT_GUARD_VERIFIERS],
        safety_boundary="Dry-run only; no mutation.",
        notes="Non-mutating dry-runs remain status-safe.",
    ),
    _action(
        "run_low_risk_self_fix_apply",
        "Run low-risk self-fix apply",
        "Low-Risk Self-Fix",
        "low",
        password_required=True,
        contract_required=True,
        verifier_required=True,
        receipt_required=True,
        dry_run_required_first=True,
        allowed_in_cli=True,
        required_contracts=["Engel Low-Risk Self-Fix Runner Contract V1"],
        required_verifiers=["tools\\verify_engel_low_risk_self_fix_runner.py", *DEFAULT_GUARD_VERIFIERS],
        required_receipt_folder="reports\\self_fix_receipts",
        safety_boundary="Only preapproved V1 low-risk classes may apply.",
        notes="No commit automation is authorized.",
    ),
    _action(
        "view_self_fix_receipts",
        "View self-fix receipts",
        "Low-Risk Self-Fix",
        "view_only",
        password_required=False,
        allowed_in_gui=True,
        allowed_in_cli=True,
        current_state="available_view_only",
        required_receipt_folder="reports\\self_fix_receipts",
        safety_boundary="Read-only receipt viewing.",
        notes="Viewing receipts does not authorize apply.",
    ),
    _action(
        "clear_stale_pid_file",
        "Clear stale PID file",
        "Low-Risk Self-Fix",
        "low",
        password_required=True,
        contract_required=True,
        verifier_required=True,
        receipt_required=True,
        dry_run_required_first=True,
        allowed_in_cli=True,
        required_contracts=["Engel Low-Risk Self-Fix Runner Contract V1"],
        required_verifiers=["tools\\verify_engel_low_risk_self_fix_runner.py", *DEFAULT_GUARD_VERIFIERS],
        required_receipt_folder="reports\\self_fix_receipts",
        safety_boundary="Only confirmed stale known PID files may be removed; no process kill.",
        notes="Password does not authorize killing a process.",
    ),
    _action(
        "run_code_companion_candidate_finder_write",
        "Run Code Companion candidate finder write",
        "Code Companion",
        "medium",
        password_required=True,
        contract_required=True,
        verifier_required=True,
        receipt_required=False,
        allowed_in_cli=True,
        required_contracts=["Engel Code Companion Intelligence Loop V1"],
        required_verifiers=["tools\\verify_engel_code_companion_candidate_finder.py", *DEFAULT_GUARD_VERIFIERS],
        required_receipt_folder="reports\\code_companion_candidates",
        safety_boundary="Candidate reports only; not patch apply.",
        notes="No source mutation or model/runtime behavior.",
    ),
    _action(
        "create_patch_candidate_write",
        "Create patch candidate write",
        "Code Companion",
        "medium",
        password_required=True,
        contract_required=True,
        verifier_required=True,
        required_contracts=["Engel Code Companion Intelligence Loop V1"],
        required_verifiers=["tools\\verify_engel_code_companion_patch_candidate.py", *DEFAULT_GUARD_VERIFIERS],
        required_receipt_folder="reports\\patch_candidates",
        safety_boundary="Patch candidate only; not applied.",
        notes="Patch candidates remain plans until separately reviewed.",
    ),
    _action(
        "create_verifier_plan_write",
        "Create verifier plan write",
        "Code Companion",
        "medium",
        password_required=True,
        contract_required=True,
        verifier_required=True,
        required_contracts=["Engel Code Companion Intelligence Loop V1"],
        required_verifiers=["tools\\verify_engel_code_companion_verifier_plan.py", *DEFAULT_GUARD_VERIFIERS],
        required_receipt_folder="reports\\verifier_plans",
        safety_boundary="Verifier plan only; not executed by creation.",
        notes="Verifier plan creation does not run verifiers.",
    ),
    _action(
        "run_code_companion_low_risk_patch_dry_run",
        "Run Code Companion low-risk patch dry-run",
        "Code Companion",
        "low",
        password_required=False,
        contract_required=True,
        verifier_required=True,
        allowed_in_cli=True,
        required_contracts=["Code Companion Low-Risk Patch Apply Contract V1"],
        required_verifiers=["tools\\verify_engel_code_companion_low_risk_patch_runner.py", *DEFAULT_GUARD_VERIFIERS],
        safety_boundary="Dry-run only; no file mutation.",
        notes="Dry-runs remain bounded to explicit patch candidate files.",
    ),
    _action(
        "run_code_companion_low_risk_patch_apply",
        "Run Code Companion low-risk patch apply",
        "Code Companion",
        "low",
        password_required=True,
        contract_required=True,
        verifier_required=True,
        receipt_required=True,
        dry_run_required_first=True,
        allowed_in_cli=True,
        required_contracts=["Code Companion Low-Risk Patch Apply Contract V1"],
        required_verifiers=["tools\\verify_engel_code_companion_low_risk_patch_runner.py", *DEFAULT_GUARD_VERIFIERS],
        required_receipt_folder="reports\\code_companion_patch_receipts",
        safety_boundary="Only implemented V1 tiny low-risk patch classes may apply.",
        notes="No commit automation is authorized.",
    ),
    _action(
        "view_code_companion_patch_receipts",
        "View Code Companion patch receipts",
        "Code Companion",
        "view_only",
        password_required=False,
        allowed_in_gui=True,
        allowed_in_cli=True,
        current_state="available_view_only",
        required_receipt_folder="reports\\code_companion_patch_receipts",
        safety_boundary="Read-only receipt viewing.",
        notes="Viewing receipts does not authorize patch application.",
    ),
    _action(
        "run_verifier_stack",
        "Run verifier stack",
        "Verifier / Safety",
        "medium",
        password_required=True,
        contract_required=True,
        verifier_required=True,
        allowed_in_cli=True,
        safety_boundary="Runs local verifiers only when the caller already has a bounded contract.",
        notes="Password does not override verifier results.",
    ),
    _action(
        "update_verifier_candidate",
        "Update verifier candidate",
        "Verifier / Safety",
        "medium",
        password_required=True,
        approval_token_required=True,
        contract_required=True,
        verifier_required=True,
        receipt_required=True,
        safety_boundary="Verifier updates require a candidate, contract, and guard review.",
        notes="No automatic verifier mutation is authorized by the registry.",
    ),
    _action(
        "apply_verifier_update",
        "Apply verifier update",
        "Verifier / Safety",
        "high",
        password_required=True,
        approval_token_required=True,
        contract_required=True,
        verifier_required=True,
        receipt_required=True,
        dry_run_required_first=True,
        safety_boundary="High-risk verifier changes require separate approval and receipt.",
        notes="Guard compatibility remains required.",
    ),
    _action("change_authority_hierarchy", "Change authority hierarchy", "Verifier / Safety", "blocked", password_required=True, current_state="blocked", blocked_reason=BLOCKED_REQUIRES_FUTURE_CONTRACT, safety_boundary="Authority hierarchy is not mutable through this layer."),
    _action("change_prompt_injection_guard", "Change prompt injection guard", "Verifier / Safety", "blocked", password_required=True, current_state="blocked", blocked_reason=BLOCKED_REQUIRES_FUTURE_CONTRACT, safety_boundary="Prompt injection guard changes require separate approval."),
    _action("change_untrusted_content_guard", "Change untrusted content guard", "Verifier / Safety", "blocked", password_required=True, current_state="blocked", blocked_reason=BLOCKED_REQUIRES_FUTURE_CONTRACT, safety_boundary="Untrusted content guard changes require separate approval."),
    _action("package_refresh", "Package refresh", "Packaging / Live App", "blocked", password_required=True, current_state="blocked", blocked_reason="package_contract_or_flow_not_active_for_this_layer", safety_boundary="No package refresh is authorized by the global password layer."),
    _action("live_exe_promotion", "Live EXE promotion", "Packaging / Live App", "blocked", password_required=True, current_state="blocked", blocked_reason="package_contract_or_flow_not_active_for_this_layer", safety_boundary="No live EXE promotion is authorized by the global password layer."),
    _action("package_smoke", "Package smoke", "Packaging / Live App", "high", password_required=True, approval_token_required=True, contract_required=True, verifier_required=True, receipt_required=True, safety_boundary="Package smoke requires package-flow authorization and remains local."),
    _action("live_process_cleanup", "Live process cleanup", "Packaging / Live App", "high", password_required=True, approval_token_required=True, contract_required=True, verifier_required=True, receipt_required=True, safety_boundary="Process cleanup requires explicit scoped approval."),
    _action("enable_provider_calls", "Enable provider calls", "Provider / Browser / Model", "blocked", password_required=True, current_state="blocked", blocked_reason=BLOCKED_REQUIRES_FUTURE_CONTRACT, safety_boundary="Provider calls remain disabled."),
    _action("enable_network", "Enable network", "Provider / Browser / Model", "blocked", password_required=True, current_state="blocked", blocked_reason=BLOCKED_REQUIRES_FUTURE_CONTRACT, safety_boundary="Network enablement remains blocked."),
    _action("enable_browser", "Enable browser", "Provider / Browser / Model", "blocked", password_required=True, current_state="blocked", blocked_reason=BLOCKED_REQUIRES_FUTURE_CONTRACT, safety_boundary="Browser enablement remains blocked."),
    _action("enable_model_runtime", "Enable model runtime", "Provider / Browser / Model", "blocked", password_required=True, current_state="blocked", blocked_reason=BLOCKED_REQUIRES_FUTURE_CONTRACT, safety_boundary="Model runtime remains disabled."),
    _action("run_local_model_inference", "Run local model inference", "Provider / Browser / Model", "blocked", password_required=True, current_state="blocked", blocked_reason=BLOCKED_REQUIRES_FUTURE_CONTRACT, safety_boundary="Model inference remains blocked."),
    _action("start_background_worker", "Start background worker", "Background / Startup", "blocked", password_required=True, current_state="blocked", blocked_reason=BLOCKED_REQUIRES_FUTURE_CONTRACT, safety_boundary="Background workers remain blocked."),
    _action("enable_startup_autorun", "Enable startup autorun", "Background / Startup", "blocked", password_required=True, current_state="blocked", blocked_reason=BLOCKED_REQUIRES_FUTURE_CONTRACT, safety_boundary="Startup autorun remains blocked."),
    _action("run_scheduled_cycle", "Run scheduled cycle", "Background / Startup", "blocked", password_required=True, current_state="blocked", blocked_reason=BLOCKED_REQUIRES_FUTURE_CONTRACT, safety_boundary="Scheduled cycles remain blocked unless separately contracted."),
    _action("remote_queen_worker_activation", "Remote queen worker activation", "Background / Startup", "blocked", password_required=True, current_state="blocked", blocked_reason=BLOCKED_REQUIRES_FUTURE_CONTRACT, safety_boundary="Remote worker activation remains blocked."),
    _action(
        "configure_global_password_gate",
        "Configure global password gate",
        "Password / Permission System",
        "medium",
        password_required=False,
        allowed_in_cli=True,
        allowed_in_gui=True,
        safety_boundary="Local prompt only; no secrets are displayed or accepted through CLI arguments.",
        notes="Setup writes only hash metadata.",
    ),
    _action(
        "change_global_password_gate",
        "Change global password gate",
        "Password / Permission System",
        "medium",
        password_required=True,
        allowed_in_cli=True,
        allowed_in_gui=True,
        safety_boundary="Requires current password and local prompt handling.",
        notes="Password changes do not grant protected action authority.",
    ),
    _action(
        "view_protected_action_registry",
        "View protected action registry",
        "Password / Permission System",
        "view_only",
        password_required=False,
        allowed_in_gui=True,
        allowed_in_cli=True,
        current_state="available_view_only",
        safety_boundary="Read-only registry display.",
        notes="Registry display executes no action.",
    ),
    _action(
        "update_protected_action_registry",
        "Update protected action registry",
        "Password / Permission System",
        "blocked",
        password_required=True,
        current_state="blocked",
        blocked_reason=BLOCKED_REQUIRES_FUTURE_CONTRACT,
        safety_boundary="Registry updates require a separate future contract.",
        notes="Blocked even with password verification.",
    ),
]

ACTION_BY_ID = {str(action["action_id"]): action for action in PROTECTED_ACTIONS}


def list_actions() -> list[dict[str, object]]:
    return [dict(action) for action in PROTECTED_ACTIONS]


def get_action(action_id: str) -> dict[str, object] | None:
    action = ACTION_BY_ID.get(action_id)
    return dict(action) if action is not None else None


def registry_summary() -> dict[str, object]:
    counts = {risk: 0 for risk in RISK_LEVELS}
    categories: dict[str, int] = {}
    password_required = 0
    for action in PROTECTED_ACTIONS:
        counts[str(action["risk_level"])] += 1
        categories[str(action["category"])] = categories.get(str(action["category"]), 0) + 1
        if action.get("password_required"):
            password_required += 1
    return {
        "status": list(REGISTRY_STATUS),
        "action_count": len(PROTECTED_ACTIONS),
        "risk_counts": counts,
        "category_counts": categories,
        "password_required_count": password_required,
        "blocked_count": counts["blocked"],
    }


def render_action_list() -> str:
    summary = registry_summary()
    lines = [
        "Engel Protected Action Registry V1",
        "",
        "Status:",
        *[f"- {status}" for status in REGISTRY_STATUS],
        "",
        "Risk counts:",
    ]
    for risk, count in summary["risk_counts"].items():
        lines.append(f"- {risk}: {count}")
    lines.extend(["", "Actions:"])
    for action in PROTECTED_ACTIONS:
        lines.append(
            f"- {action['action_id']} | {action['category']} | {action['risk_level']} | "
            f"password_required={action['password_required']} | state={action['current_state']}"
        )
    lines.extend(
        [
            "",
            "Boundary:",
            "- This registry describes gates only; it does not execute protected actions.",
            "- Blocked actions remain blocked even with password verification.",
            "- Password protects actions; it does not bypass safety.",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def render_action_detail(action_id: str) -> str:
    action = get_action(action_id)
    if action is None:
        return "Unknown protected action.\n"
    lines = ["Engel Protected Action", ""]
    for field in REQUIRED_ACTION_FIELDS:
        value = action.get(field)
        if isinstance(value, list):
            rendered = ", ".join(str(item) for item in value) if value else "none"
        else:
            rendered = str(value)
        lines.append(f"{field}: {rendered}")
    return "\n".join(lines).rstrip() + "\n"


def registry_payload() -> dict[str, object]:
    return {
        "schema_version": "1.0",
        "status": list(REGISTRY_STATUS),
        "required_action_fields": list(REQUIRED_ACTION_FIELDS),
        "risk_levels": list(RISK_LEVELS),
        "summary": registry_summary(),
        "actions": list_actions(),
        "boundary": "Registry only; no action execution.",
    }


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Read Engel protected action registry.")
    parser.add_argument("--list", action="store_true", help="List registered protected actions.")
    parser.add_argument("--show", metavar="ACTION_ID", help="Show one protected action.")
    parser.add_argument("--json", action="store_true", help="Print registry JSON.")
    return parser


def main(argv: list[str] | None = None, stdout=None, stderr=None) -> int:
    out = sys.stdout if stdout is None else stdout
    err = sys.stderr if stderr is None else stderr
    args = build_parser().parse_args(argv)
    modes = [args.list, bool(args.show), args.json]
    if not any(modes):
        out.write(render_action_list())
        return 0
    if sum(1 for mode in modes if mode) != 1:
        err.write("Choose exactly one registry display mode.\n")
        return 2
    if args.list:
        out.write(render_action_list())
        return 0
    if args.json:
        out.write(json.dumps(registry_payload(), indent=2, sort_keys=True) + "\n")
        return 0
    action = get_action(str(args.show))
    if action is None:
        err.write("Unknown protected action.\n")
        return 1
    out.write(render_action_detail(str(args.show)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
