#!/usr/bin/env python3
from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
WORKSPACE_TEXT = r"D:\b.WorkSpace\Engel App"

CONTRACT_ID = "ENGEL_DEBRUIJN_QUANTUM_BUILD_PROMOTE_GRAPH_ALIGNMENT_CONTRACT_V1"
CONTRACT_JSON = ROOT / "memory" / f"{CONTRACT_ID}.json"
CONTRACT_MD = ROOT / "memory" / f"{CONTRACT_ID}.md"
CONTRACT_REPORT = ROOT / "reports" / "codex_bridge" / f"{CONTRACT_ID}.md"

PASS_MARKER = "DEBRUIJN_QUANTUM_BUILD_PROMOTE_GRAPH_ALIGNMENT_CONTRACT_VERIFICATION_PASS"

REQUIRED_FILES = [
    CONTRACT_JSON,
    CONTRACT_MD,
    CONTRACT_REPORT,
]

RELATED_FILES = [
    ROOT / "memory" / "ENGEL_DEBRUIJN_GRAPH_SEQUENCE_MODEL_V1.json",
    ROOT / "tools" / "verify_debruijn_graph_sequence_model.py",
    ROOT / "memory" / "ENGEL_DEBRUIJN_QUANTUM_RUNTIME_ENGINE_GRAPH_ALIGNMENT_CONTRACT_V1.json",
    ROOT / "tools" / "verify_debruijn_quantum_runtime_engine_graph_alignment_contract.py",
    ROOT / "memory" / "ENGEL_DEBRUIJN_QUANTUM_APPLY_ENGINE_GRAPH_ALIGNMENT_CONTRACT_V1.json",
    ROOT / "tools" / "verify_debruijn_quantum_apply_engine_graph_alignment_contract.py",
    ROOT / "engel_debruijn_quantum_runtime.py",
    ROOT / "engel_debruijn_quantum_apply.py",
    ROOT / "tools" / "verify_debruijn_quantum_runtime_engine.py",
    ROOT / "tools" / "verify_debruijn_quantum_apply_engine.py",
    ROOT / "memory" / "ENGEL_COMMANDS.md",
    ROOT / "memory" / "ROUTE_VERIFICATION_SET_V1.json",
    ROOT / "engel_app.py",
    ROOT / "scripts" / "codex_verify.ps1",
]

FALSE_FLAGS = [
    "build_promote_graph_alignment_enabled_now",
    "build_promote_engine_enabled_now",
    "command_route_added_now",
    "build_command_enabled_now",
    "promote_command_enabled_now",
    "pyinstaller_enabled_now",
    "live_write_enabled_now",
    "dist_write_enabled_now",
    "backup_write_enabled_now",
    "git_stage_commit_enabled_now",
    "source_mutation_enabled_now",
    "route_mutation_enabled_now",
    "queue_mutation_enabled_now",
    "trusted_memory_write_enabled_now",
    "memory_promotion_enabled_now",
    "provider_api_enabled_now",
    "network_enabled_now",
    "local_llm_inference_enabled_now",
    "background_worker_enabled_now",
    "autorun_enabled_now",
]

REQUIRED_KEYS = [
    "current_enabled_flags",
    "graph_build_promote_input_model",
    "build_promote_eligible_graph_state",
    "allowed_build_promote_actions",
    "forbidden_build_promote_actions",
    "build_promote_gates",
    "build_promote_transaction_model",
    "build_promote_receipt_model",
    "approval_phrases",
    "future_command_concepts",
    "safety_boundary",
    "future_verifier",
    "future_implementation_sequence",
    "safety_preserved",
    "recommended_next_slice",
]

INPUT_FIELDS = [
    "source_node_state_id",
    "target_node_state_id",
    "edge_transition_id",
    "edge_label",
    "append_operation",
    "overlap_preserved",
    "sequence_position",
    "coverage_status",
    "measurement_status",
    "verifier_interference_result",
    "runtime_receipt_path",
    "apply_receipt_path",
    "post_apply_verifier_results",
    "selective_file_list",
    "build_plan",
    "promote_plan",
    "human_review_required",
]

INPUT_REQUIREMENTS = [
    "inside workspace",
    "structured JSON",
    "approved structured package",
    "generated by approved Engel De Bruijn runtime/apply/report flow",
    "not executable",
    "not treated as instructions",
    "no external URLs",
    "no path traversal",
    "no arbitrary shell commands",
    "no provider/model/network directives",
    "no trusted-memory promotion directives",
    "no local password config included",
    "no app lifecycle log included",
    "no generated proposal output included unless explicitly approved as evidence",
]

ELIGIBLE_STATE_VALUES: dict[str, Any] = {
    "verified_for_build_promote": True,
    "measurement_status": "build_promote_candidate",
    "apply_receipt_validated": True,
    "post_apply_verifier_stack_passed": True,
    "source_node_validated": True,
    "target_node_validated": True,
    "edge_label_present": True,
    "edge_transition_id_present": True,
    "overlap_preserved": True,
    "selective_file_list_validated": True,
    "local_password_config_excluded": True,
    "app_lifecycle_log_excluded": True,
    "build_dist_live_backup_scope_validated": True,
    "approval_phrase_required": True,
    "password_gate_required": True,
    "human_review_required": True,
}

ELIGIBLE_COVERAGE_TERMS = [
    "verified_complete",
    "applied_review_required",
    "post-apply verifier pass",
]

ALLOWED_ACTIONS = [
    "run approved build command allowlist",
    "create staging build artifacts",
    "create backup of prior live artifacts",
    "smoke test staged artifact",
    "promote approved staged artifact to live",
    "write build/promote receipts",
    "update approved backend status docs",
    "update release/checkpoint reports",
]

ALLOWED_REQUIREMENTS = [
    "specific graph edge/sequence position",
    "explicit approval phrase",
    "Global Password Gate",
    "clean verifier state",
    "selective file list",
    "local password config exclusion",
    "generated/untrusted evidence exclusion unless explicitly approved",
    "receipt evidence",
    "human_review_required true",
]

FORBIDDEN_TERMS = [
    "automatic build from traversal",
    "automatic promote from traversal",
    "build without approved apply",
    "build without full verifier pass",
    "promote without smoke test",
    "local password config",
    "app lifecycle log",
    "code_workspace",
    "build/dist/live/backups",
    "trusted-memory/training artifacts",
    "untrusted proposal outputs as source truth",
    "rewrite history",
    "git add .",
    "git add -A",
    "broad wildcard staging",
    "provider/network/model/local LLM",
    "package install",
    "source/route/queue/trusted-memory mutation outside approved apply flow",
    "memory promotion",
    "background worker",
    "scheduler/startup hook",
    "password/salt/hash exposure",
]

BEFORE_BUILD_GATES = [
    "build/promote graph alignment contract exists",
    "build/promote graph alignment verifier passes",
    "graph sequence model verifier passes",
    "runtime graph alignment verifier passes",
    "apply graph alignment verifier passes",
    "runtime engine verifier passes",
    "apply engine verifier passes",
    "authority hierarchy passes",
    "prompt injection guard passes",
    "untrusted-content verifier passes",
    "De Bruijn import boundary verifier passes",
    "Global Password Gate verifier passes",
    "post-apply verifier stack passes",
    "build candidate has graph edge label",
    "verified_for_build_promote true",
    "approval phrase present",
    "password gate runtime check passes, redacted",
    "local password config excluded",
    "app lifecycle log excluded",
    "selective file list validated",
    "no unapproved dirty files in build plan",
]

AFTER_BUILD_GATES = [
    "build receipt written",
    "staged artifact smoke tested",
    "no live promotion yet unless promote gate passes",
    "no provider/model/network side effects",
    "no trusted-memory write",
    "human_review_required remains true",
]

BEFORE_PROMOTE_GATES = [
    "build receipt valid",
    "staged smoke test passed",
    "promotion approval phrase present",
    "Global Password Gate passes",
    "backup plan validated",
    "live target validated",
    "no local password config included",
    "final verifier check passes",
]

AFTER_PROMOTE_GATES = [
    "promote receipt written",
    "live smoke test performed",
    "final process cleanup complete",
    "final verifier/sanity checks pass",
    "human_review_required remains true",
    "no autonomous future loop enabled",
]

TRANSACTION_STEPS = [
    "preflight_read",
    "validate_graph_build_candidate",
    "validate_runtime_apply_receipts",
    "validate_selective_file_list",
    "validate_exclusions",
    "run_pre_build_verifiers",
    "run_approved_build_command",
    "write_build_receipt",
    "smoke_test_staged_artifact",
    "validate_promote_gate",
    "backup_previous_live_artifacts",
    "promote_staged_artifact",
    "smoke_test_live_artifact",
    "write_promote_receipt",
    "run_final_verifiers",
    "classify_result",
]

TRANSACTION_ROLLBACK_TERMS = [
    "no automatic destructive rollback unless separately approved",
    "backup notes",
    "hash manifest",
    "PROMOTED_REVIEW_REQUIRED",
    "PROMOTE_BLOCKED",
    "evidence/backups are not deleted",
]

BUILD_RECEIPT_FIELDS = [
    "receipt_id",
    "engine_id",
    "action_type",
    "started_at",
    "ended_at",
    "input_build_candidate_path",
    "source_node_state_id",
    "target_node_state_id",
    "edge_transition_id",
    "edge_label",
    "append_operation",
    "overlap_preserved",
    "sequence_position",
    "coverage_status_before",
    "coverage_status_after",
    "measurement_status_before",
    "measurement_status_after",
    "verifier_interference_result",
    "approval_detected",
    "approval_phrase_name",
    "password_gate_result",
    "selective_file_list",
    "excluded_files",
    "pre_build_verifier_results",
    "build_command_id",
    "build_outputs",
    "staged_artifact_paths",
    "staged_smoke_result",
    "forbidden_actions_not_performed",
    "final_status",
    "human_review_required",
]

PROMOTE_RECEIPT_FIELDS = [
    "receipt_id",
    "engine_id",
    "action_type",
    "started_at",
    "ended_at",
    "input_build_receipt_path",
    "approval_detected",
    "approval_phrase_name",
    "password_gate_result",
    "backup_paths",
    "promoted_artifact_paths",
    "live_smoke_result",
    "final_verifier_results",
    "forbidden_actions_not_performed",
    "final_status",
    "human_review_required",
]

FUTURE_COMMAND_TERMS = [
    "engel ai debruijn quantum build APPROVE_DEBRUIJN_QUANTUM_GRAPH_BUILD_V1 candidate=<candidate_path>",
    "engel ai debruijn quantum promote APPROVE_DEBRUIJN_QUANTUM_GRAPH_PROMOTE_V1 build_receipt=<receipt_path>",
    "exact approval phrase",
    "password gate",
    "graph edge label",
    "verified_for_build_promote",
    "candidate/receipt path inside workspace",
    "reject external URLs",
    "reject path traversal",
    "reject arbitrary extra args",
    "reject output path override",
    "reject shell commands from candidate",
    "reject provider/model/network args",
    "fail closed on missing verifier/gate",
    "contract-only",
    "no commands or routes are implemented now",
]

EXPECTED_SEQUENCE = [
    "ENGEL_DEBRUIJN_QUANTUM_BUILD_PROMOTE_GRAPH_ALIGNMENT_CONTRACT_V1",
    "ENGEL_DEBRUIJN_QUANTUM_BUILD_PROMOTE_GRAPH_ALIGNMENT_VERIFIER_V1",
    "ENGEL_DEBRUIJN_QUANTUM_BUILD_PROMOTE_ENGINE_CONTRACT_V1",
    "ENGEL_DEBRUIJN_QUANTUM_BUILD_PROMOTE_ENGINE_VERIFIER_V1",
    "ENGEL_DEBRUIJN_QUANTUM_BUILD_PROMOTE_ENGINE_V1",
    "ENGEL_DEBRUIJN_QUANTUM_BUILD_PROMOTE_ENGINE_SOURCE_SMOKE_V1",
    "ENGEL_DEBRUIJN_QUANTUM_BUILD_PROMOTE_CLOSEOUT_REVIEW_V1",
]

EXCLUDED_DIRS = {
    ".git",
    "build",
    "dist",
    "live",
    "backups",
    "__pycache__",
    ".venv",
    "venv",
    "node_modules",
    "reports",
    "memory",
}

SCAN_SUFFIXES = {".py", ".ps1", ".json", ".toml", ".yaml", ".yml", ".bat", ".cmd", ".md"}

ACTIVE_PATTERNS = [
    ("build/promote module", re.compile(r"engel_debruijn_quantum_build_promote\.py", re.IGNORECASE)),
    ("build/promote engine implementation", re.compile(r"debruijn_quantum_build_promote_engine", re.IGNORECASE)),
    ("De Bruijn build route", re.compile(r"engel\s+ai\s+debruijn\s+quantum\s+build", re.IGNORECASE)),
    ("De Bruijn promote route", re.compile(r"engel\s+ai\s+debruijn\s+quantum\s+promote", re.IGNORECASE)),
    ("graph build approval phrase route", re.compile(r"APPROVE_DEBRUIJN_QUANTUM_GRAPH_BUILD_V1", re.IGNORECASE)),
    ("graph promote approval phrase route", re.compile(r"APPROVE_DEBRUIJN_QUANTUM_GRAPH_PROMOTE_V1", re.IGNORECASE)),
    ("build promote graph alignment true", re.compile(r"build_promote_graph_alignment_enabled_now\s*[:=]\s*true", re.IGNORECASE)),
    ("build promote engine true", re.compile(r"build_promote_engine_enabled_now\s*[:=]\s*true", re.IGNORECASE)),
    ("build command true", re.compile(r"build_command_enabled_now\s*[:=]\s*true", re.IGNORECASE)),
    ("promote command true", re.compile(r"promote_command_enabled_now\s*[:=]\s*true", re.IGNORECASE)),
    ("pyinstaller true", re.compile(r"pyinstaller_enabled_now\s*[:=]\s*true", re.IGNORECASE)),
    ("live write true", re.compile(r"live_write_enabled_now\s*[:=]\s*true", re.IGNORECASE)),
    ("dist write true", re.compile(r"dist_write_enabled_now\s*[:=]\s*true", re.IGNORECASE)),
    ("backup write true", re.compile(r"backup_write_enabled_now\s*[:=]\s*true", re.IGNORECASE)),
    ("git stage commit true", re.compile(r"git_stage_commit_enabled_now\s*[:=]\s*true", re.IGNORECASE)),
    ("auto build", re.compile(r"auto[_\s-]*build", re.IGNORECASE)),
    ("auto promote", re.compile(r"auto[_\s-]*promote", re.IGNORECASE)),
    ("subprocess pyinstaller", re.compile(r"subprocess[^\n]{0,140}pyinstaller", re.IGNORECASE)),
    ("subprocess build", re.compile(r"subprocess[^\n]{0,140}\bbuild\b", re.IGNORECASE)),
    ("subprocess promote", re.compile(r"subprocess[^\n]{0,140}\bpromote\b", re.IGNORECASE)),
    ("git add dot", re.compile(r"\bgit\s+add\s+\.", re.IGNORECASE)),
    ("git add all", re.compile(r"\bgit\s+add\s+-A\b", re.IGNORECASE)),
    ("git commit", re.compile(r"\bgit\s+commit\b", re.IGNORECASE)),
    ("package install", re.compile(r"\b(pip|uv|poetry|npm)\s+(install|add)\b", re.IGNORECASE)),
    ("provider network model", re.compile(r"provider.*network.*model|network.*model.*provider", re.IGNORECASE)),
    ("local llm", re.compile(r"local[_\s-]*llm", re.IGNORECASE)),
    ("background autorun scheduler", re.compile(r"background|autorun|scheduler|startup", re.IGNORECASE)),
]

SAFE_LINE_MARKERS = [
    "forbid",
    "forbidden",
    "must not",
    "do not",
    "never",
    "disabled",
    "future",
    "future-only",
    "contract",
    "contract_only",
    "review_required",
    "verifier",
    "scan",
    "pattern",
    "reject",
    "no ",
    "no_",
    "not implemented",
    "fail closed",
    "false",
]


class Check:
    def __init__(self) -> None:
        self.failures: list[str] = []
        self.review_required: list[str] = []

    def line(self, level: str, message: str) -> None:
        safe_message = message.encode("ascii", "backslashreplace").decode("ascii")
        print(f"{level} {safe_message}", flush=True)

    def pass_(self, message: str) -> None:
        self.line("PASS", message)

    def fail(self, message: str) -> None:
        self.failures.append(message)
        self.line("FAIL", message)

    def info(self, message: str) -> None:
        self.line("INFO", message)

    def skip(self, message: str) -> None:
        self.line("SKIP", message)

    def review(self, message: str) -> None:
        self.review_required.append(message)
        self.line("REVIEW_REQUIRED", message)


def rel(path: Path) -> str:
    try:
        return str(path.resolve(strict=False).relative_to(ROOT.resolve(strict=False))).replace("/", "\\")
    except ValueError:
        return str(path)


def normalize(value: Any) -> str:
    text = value if isinstance(value, str) else json.dumps(value, sort_keys=True, ensure_ascii=True)
    text = text.lower().replace("\\", " ")
    text = re.sub(r"[^a-z0-9_.<>=:-]+", " ", text)
    return re.sub(r"\s+", " ", text).strip()


def has_term(blob: str, term: str) -> bool:
    return normalize(term) in blob


def require_terms(check: Check, label: str, value: Any, terms: list[str]) -> None:
    blob = normalize(value)
    missing = [term for term in terms if not has_term(blob, term)]
    if missing:
        check.fail(f"{label} missing required terms: {', '.join(missing)}")
    else:
        check.pass_(f"{label} contains required terms")


def read_required(check: Check) -> dict[str, Any] | None:
    missing = [path for path in REQUIRED_FILES if not path.exists()]
    if missing:
        for path in missing:
            check.fail(f"required build/promote graph-alignment contract file missing: {rel(path)}")
        return None
    for path in REQUIRED_FILES:
        check.pass_(f"required build/promote graph-alignment contract file exists: {rel(path)}")
    try:
        data = json.loads(CONTRACT_JSON.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        check.fail(f"contract JSON is invalid: {exc}")
        return None
    if not isinstance(data, dict):
        check.fail("contract JSON top-level value must be an object")
        return None
    check.pass_("contract JSON parsed")
    return data


def inspect_related(check: Check) -> None:
    for path in RELATED_FILES:
        if path.exists():
            check.info(f"related file present for context: {rel(path)}")
        else:
            check.skip(f"related file not present: {rel(path)}")


def check_identity_and_flags(check: Check, data: dict[str, Any]) -> None:
    expected = {
        "contract_id": CONTRACT_ID,
        "status": "contract_only",
        "active_workspace": WORKSPACE_TEXT,
        "future_engine_id": "debruijn_quantum_build_promote_engine",
        "future_module": "engel_debruijn_quantum_build_promote.py",
        "source_model_contract": "ENGEL_DEBRUIJN_GRAPH_SEQUENCE_MODEL_V1",
        "runtime_graph_alignment_dependency": "ENGEL_DEBRUIJN_QUANTUM_RUNTIME_ENGINE_GRAPH_ALIGNMENT_CONTRACT_V1",
        "apply_graph_alignment_dependency": "ENGEL_DEBRUIJN_QUANTUM_APPLY_ENGINE_GRAPH_ALIGNMENT_CONTRACT_V1",
    }
    for key, value in expected.items():
        if data.get(key) == value:
            check.pass_(f"{key} matches expected value")
        else:
            check.fail(f"{key} expected {value!r}, got {data.get(key)!r}")

    missing = [key for key in REQUIRED_KEYS if key not in data]
    if missing:
        check.fail(f"contract JSON missing required keys: {', '.join(missing)}")
    else:
        check.pass_("contract JSON includes all required top-level keys")

    flags = data.get("current_enabled_flags")
    if not isinstance(flags, dict):
        check.fail("current_enabled_flags must be an object")
        flags = {}
    for flag in FALSE_FLAGS:
        top = data.get(flag)
        nested = flags.get(flag)
        if top is False and nested is False:
            check.pass_(f"{flag} is false at top level and in current_enabled_flags")
        else:
            check.fail(f"{flag} must be false at top level and in current_enabled_flags")


def check_input_and_eligible_state(check: Check, data: dict[str, Any]) -> None:
    input_model = data.get("graph_build_promote_input_model")
    require_terms(check, "graph_build_promote_input_model fields", input_model, INPUT_FIELDS)
    require_terms(check, "graph_build_promote_input_model requirements", input_model, INPUT_REQUIREMENTS)

    eligible = data.get("build_promote_eligible_graph_state")
    if not isinstance(eligible, dict):
        check.fail("build_promote_eligible_graph_state must be an object")
        return
    required_state = eligible.get("required_state")
    if not isinstance(required_state, dict):
        check.fail("build_promote_eligible_graph_state.required_state must be an object")
        return
    for key, expected in ELIGIBLE_STATE_VALUES.items():
        if required_state.get(key) == expected:
            check.pass_(f"build_promote_eligible_graph_state requires {key} == {expected!r}")
        else:
            check.fail(f"build_promote_eligible_graph_state {key} expected {expected!r}, got {required_state.get(key)!r}")
    require_terms(check, "build_promote_eligible_graph_state coverage", required_state.get("coverage_status"), ELIGIBLE_COVERAGE_TERMS)
    require_terms(
        check,
        "build_promote_eligible_graph_state trust rule",
        eligible,
        [
            "verified_for_build_promote is not trusted autonomous permission",
            "eligible for an explicitly approved",
            "password-gated build/promote attempt",
        ],
    )


def check_actions_and_gates(check: Check, data: dict[str, Any]) -> None:
    allowed = data.get("allowed_build_promote_actions")
    require_terms(check, "allowed_build_promote_actions allowed set", allowed, ALLOWED_ACTIONS)
    require_terms(check, "allowed_build_promote_actions requirements", allowed, ALLOWED_REQUIREMENTS)

    require_terms(check, "forbidden_build_promote_actions", data.get("forbidden_build_promote_actions"), FORBIDDEN_TERMS)
    require_terms(check, "safety_boundary forbidden behavior", data.get("safety_boundary"), FORBIDDEN_TERMS)

    gates = data.get("build_promote_gates")
    if not isinstance(gates, dict):
        check.fail("build_promote_gates must be an object")
        return
    require_terms(check, "build_promote_gates before_build", gates.get("before_build"), BEFORE_BUILD_GATES)
    require_terms(check, "build_promote_gates after_build", gates.get("after_build"), AFTER_BUILD_GATES)
    require_terms(check, "build_promote_gates before_promote", gates.get("before_promote"), BEFORE_PROMOTE_GATES)
    require_terms(check, "build_promote_gates after_promote", gates.get("after_promote"), AFTER_PROMOTE_GATES)


def check_transaction_receipt_command(check: Check, data: dict[str, Any]) -> None:
    transaction = data.get("build_promote_transaction_model")
    require_terms(check, "build_promote_transaction_model steps", transaction, TRANSACTION_STEPS)
    require_terms(check, "build_promote_transaction_model rollback policy", transaction, TRANSACTION_ROLLBACK_TERMS)

    receipt = data.get("build_promote_receipt_model")
    require_terms(
        check,
        "build_promote_receipt_model folders",
        receipt,
        ["reports\\debruijn_quantum_build_receipts\\", "reports\\debruijn_quantum_promote_receipts\\"],
    )
    require_terms(check, "build_promote_receipt_model build fields", receipt, BUILD_RECEIPT_FIELDS)
    require_terms(check, "build_promote_receipt_model promote fields", receipt, PROMOTE_RECEIPT_FIELDS)
    require_terms(check, "build_promote_receipt_model secret exclusion", receipt, ["password/salt/hash values"])

    approval = data.get("approval_phrases")
    require_terms(
        check,
        "approval_phrases",
        approval,
        ["APPROVE_DEBRUIJN_QUANTUM_GRAPH_BUILD_V1", "APPROVE_DEBRUIJN_QUANTUM_GRAPH_PROMOTE_V1"],
    )

    command = data.get("future_command_concepts")
    require_terms(check, "future_command_concepts", command, FUTURE_COMMAND_TERMS)


def check_future_verifier_and_sequence(check: Check, data: dict[str, Any]) -> None:
    future_verifier = data.get("future_verifier")
    require_terms(
        check,
        "future_verifier",
        future_verifier,
        [
            "tools\\verify_debruijn_quantum_build_promote_graph_alignment_contract.py",
            "contract exists",
            "current enabled flags false",
            "build/promote input model exists",
            "eligible graph state exists",
            "allowed/forbidden build/promote actions documented",
            "build/promote gates documented",
            "transaction model documented",
            "receipt model documented",
            "approval phrases documented",
            "future commands are contract-only",
            "no build/promote module or route exists yet",
            "graph model verifier passes",
            "runtime graph alignment verifier passes",
            "apply graph alignment verifier passes",
        ],
    )

    sequence = data.get("future_implementation_sequence")
    if not isinstance(sequence, list):
        check.fail("future_implementation_sequence must be a list")
    else:
        missing = [item for item in EXPECTED_SEQUENCE if item not in sequence]
        if missing:
            check.fail(f"future_implementation_sequence missing: {', '.join(missing)}")
        else:
            positions = [sequence.index(item) for item in EXPECTED_SEQUENCE]
            if positions == sorted(positions):
                check.pass_("future_implementation_sequence contains required ordered slices")
            else:
                check.fail("future_implementation_sequence contains required entries out of order")

    require_terms(
        check,
        "safety_preserved",
        data.get("safety_preserved"),
        [
            "contract_only",
            "no_build_promote_source_changed",
            "no_build_promote_module_created",
            "no_runtime_source_changed",
            "no_apply_source_changed",
            "no_command_route_added",
            "no_write_to_live_dist_build_backups",
            "no_staging_or_commit",
            "no_password_values_exposed",
        ],
    )

    if data.get("recommended_next_slice") == "ENGEL_DEBRUIJN_QUANTUM_BUILD_PROMOTE_GRAPH_ALIGNMENT_VERIFIER_V1":
        check.pass_("recommended_next_slice points to build/promote graph-alignment verifier")
    else:
        check.fail("recommended_next_slice must be ENGEL_DEBRUIJN_QUANTUM_BUILD_PROMOTE_GRAPH_ALIGNMENT_VERIFIER_V1")


def should_scan(path: Path) -> bool:
    try:
        parts = path.resolve(strict=False).relative_to(ROOT.resolve(strict=False)).parts
    except ValueError:
        return False
    if any(part in EXCLUDED_DIRS for part in parts):
        return False
    if path == Path(__file__).resolve():
        return False
    if len(parts) >= 2 and parts[0] == "tools" and path.name.startswith("verify_"):
        return False
    return path.suffix.lower() in SCAN_SUFFIXES


def safe_line(line: str) -> bool:
    lower = line.lower()
    return any(marker in lower for marker in SAFE_LINE_MARKERS)


def line_has_build_promote_context(line: str) -> bool:
    lower = line.lower()
    return (
        "debruijn" in lower
        or "build_promote" in lower
        or "build/promote" in lower
        or "quantum graph build" in lower
        or "quantum graph promote" in lower
    )


def file_has_v1_fail_closed_marker(text: str) -> bool:
    """A file with the V1 disabled-reason marker is recognised as carrying fail-closed
    approved-build/promote command wiring (not active graph-alignment behaviour). The
    runtime route verifiers independently enforce that the V1 handlers stay
    fail-closed.
    """
    return (
        "APPROVED_BUILD_EXECUTION_NOT_IMPLEMENTED" in text
        or "PROMOTE_EXECUTION_NOT_IMPLEMENTED" in text
    )


V1_WIRING_LINE_MARKERS = [
    "approved_build_command_prefix_v1",
    "approved_build_command_approval_phrase_v1",
    "approved_build_command_contract_id_v1",
    "approved_build_disabled_reason_v1",
    "approved_build_forbidden_flags_v1",
    "debruijn_quantum_approved_build_command_v1",
    "approved_promote_command_prefix_v1",
    "approved_promote_command_approval_phrase_v1",
    "approved_promote_command_contract_id_v1",
    "approved_promote_disabled_reason_v1",
    "approved_promote_forbidden_flags_v1",
    "debruijn_quantum_approved_promote_command_v1",
    'debruijn_msg.startswith("engel ai debruijn quantum build")',
    'debruijn_msg.startswith("engel ai debruijn quantum promote")',
    'msg.lower().startswith("engel ai debruijn quantum build")',
    'msg.lower().startswith("engel ai debruijn quantum promote")',
    '"pattern": "engel ai debruijn quantum build"',
    '"pattern": "engel ai debruijn quantum promote"',
    "approved_build_command_fail_closed_preflight_only_v1",
    "approved_promote_command_fail_closed_preflight_only_v1",
    "engel ai debruijn quantum build approve_debruijn_quantum_graph_build_v1 candidate=<candidate_path>",
    "engel ai debruijn quantum promote approve_debruijn_quantum_graph_promote_v1 build_receipt=<receipt_path>",
]


def line_is_v1_wiring(line: str) -> bool:
    lower = line.lower()
    return any(marker.lower() in lower for marker in V1_WIRING_LINE_MARKERS)


APPROVED_BUILD_LANE_V1_LINE_MARKERS = [
    "approved_build_lane_id",
    "approved_build_lane_contract_id",
    "approved_build_approval_phrase",
    "approved_build_lane_not_implemented",
    "approved_build_lane_blocked_script_missing",
    "approved_build_lane_blocked_pre_verifier",
    "approved_build_lane_blocked_password_gate",
    "approved_build_lane_blocked_timeout_lane_missing",
    "approved_build_lane_blocked_outside_allowlist",
    "approved_build_lane_v1_present",
    "approved_build_lane_v1_final_status_without_scripts",
    "approved_build_lane_status",
    "approved build lane v1",
    "build_lane_blocked_script_missing",
    "def get_approved_build_lane_contract",
    "def get_approved_build_lane_allowlist",
    "def approved_build_lane_receipt_payload",
    "def write_approved_build_lane_receipt",
    "def run_approved_graph_build",
    "run_approved_graph_build",
    "approval_phrase != approved_build_approval_phrase",
    "approval_phrase == approved_build_approval_phrase",
    "approval_phrase_name",
    "debruijn_quantum_approved_build_lane_",
]


def line_is_approved_build_lane_v1_allowed(path: Path, line: str, file_text: str) -> bool:
    if path.name != "engel_debruijn_quantum_build_promote.py":
        return False
    lower_text = file_text.lower()
    if "def run_approved_graph_build(" not in lower_text:
        return False
    if "build_lane_blocked_script_missing" not in lower_text:
        return False
    if "subprocess." in lower_text:
        return False
    lower_line = line.lower()
    return any(marker in lower_line for marker in APPROVED_BUILD_LANE_V1_LINE_MARKERS)


APPROVED_PROMOTE_LANE_V1_LINE_MARKERS = [
    "approved_promote_lane_id",
    "approved_promote_lane_contract_id",
    "approved_promote_approval_phrase",
    "approved_promote_lane_not_implemented",
    "approved_promote_lane_blocked_build_receipt_missing",
    "approved_promote_lane_blocked_build_receipt_invalid",
    "approved_promote_lane_blocked_staged_artifact_missing",
    "approved_promote_lane_blocked_outside_allowlist",
    "approved_promote_lane_blocked_pre_verifier",
    "approved_promote_lane_blocked_password_gate",
    "approved_promote_lane_blocked_timeout_lane_missing",
    "promote_lane_blocked_staged_artifact_missing",
    "promote_lane_not_implemented",
    "def get_approved_promote_lane_contract",
    "def get_approved_promote_lane_allowlist",
    "def write_approved_promote_lane_receipt",
    "def run_approved_graph_promote",
    "run_approved_graph_promote",
    "approval_phrase != approved_promote_approval_phrase",
    "approval_phrase == approved_promote_approval_phrase",
    "debruijn_quantum_approved_promote_lane_",
]


def line_is_approved_promote_lane_v1_allowed(path: Path, line: str, file_text: str) -> bool:
    if path.name != "engel_debruijn_quantum_build_promote.py":
        return False
    lower_text = file_text.lower()
    if "def run_approved_graph_promote(" not in lower_text:
        return False
    if "promote_lane_blocked_staged_artifact_missing" not in lower_text and "promote_lane_not_implemented" not in lower_text:
        return False
    if "subprocess." in lower_text:
        return False
    lower_line = line.lower()
    return any(marker in lower_line for marker in APPROVED_PROMOTE_LANE_V1_LINE_MARKERS)


def preflight_module_is_safe(path: Path) -> bool:
    try:
        text = path.read_text(encoding="utf-8", errors="ignore").lower()
    except OSError:
        return False
    required = [
        "actual_build_enabled = false",
        "actual_promote_enabled = false",
        "pyinstaller_enabled = false",
        "live_write_enabled = false",
        "approved_build_execution_not_implemented",
        "build_preflight_only",
        "promote_preflight_only",
    ]
    forbidden = [
        "subprocess.",
        "os.system",
        "pyinstaller_enabled = true",
        "actual_build_enabled = true",
        "actual_promote_enabled = true",
        "live_write_enabled = true",
        "dist_write_enabled = true",
        "backup_write_enabled = true",
        "git_stage_commit_enabled = true",
    ]
    return all(item in text for item in required) and not any(item in text for item in forbidden)


def active_source_scan(check: Check) -> None:
    findings: list[str] = []
    review_notes: list[str] = []
    scanned = 0

    module_path = ROOT / "engel_debruijn_quantum_build_promote.py"
    if module_path.exists():
        if preflight_module_is_safe(module_path):
            check.info("engel_debruijn_quantum_build_promote.py exists as verified preflight-only disabled helper")
        else:
            findings.append("engel_debruijn_quantum_build_promote.py exists without required preflight-only safety literals")

    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [name for name in dirnames if name not in EXCLUDED_DIRS and not name.startswith(".")]
        for filename in filenames:
            path = Path(dirpath) / filename
            if not should_scan(path):
                continue
            scanned += 1
            try:
                text = path.read_text(encoding="utf-8", errors="ignore")
            except OSError as exc:
                review_notes.append(f"could not read active source file {rel(path)}: {exc}")
                continue
            v1_fail_closed_file = file_has_v1_fail_closed_marker(text)
            for lineno, line in enumerate(text.splitlines(), start=1):
                if safe_line(line):
                    continue
                if v1_fail_closed_file and line_is_v1_wiring(line):
                    continue
                if line_is_approved_build_lane_v1_allowed(path, line, text):
                    continue
                if line_is_approved_promote_lane_v1_allowed(path, line, text):
                    continue
                for label, pattern in ACTIVE_PATTERNS:
                    if not pattern.search(line):
                        continue
                    if label in {
                        "package install",
                        "provider network model",
                        "local llm",
                        "background autorun scheduler",
                        "subprocess build",
                        "subprocess promote",
                        "subprocess pyinstaller",
                        "git commit",
                        "git add dot",
                        "git add all",
                        "auto build",
                        "auto promote",
                    } and not line_has_build_promote_context(line):
                        continue
                    location = f"{rel(path)}:{lineno}: {label}: {line.strip()[:160]}"
                    if line_has_build_promote_context(line) or "APPROVE_DEBRUIJN_QUANTUM_GRAPH_" in line:
                        findings.append(location)
                    else:
                        review_notes.append(location)

    check.info(f"active source scan inspected {scanned} source/config files")
    for note in review_notes:
        check.review(f"active source scan review-only finding {note}")
    if findings:
        for finding in findings:
            check.fail(f"active build/promote graph-alignment behavior found: {finding}")
    else:
        check.pass_("active source scan found no active build/promote graph-alignment behavior")


def finish(check: Check) -> int:
    if check.review_required and not check.failures:
        check.info(f"review-required notes emitted: {len(check.review_required)}")
    if check.failures:
        check.info(f"verification failed with {len(check.failures)} failure(s)")
        return 1
    print(PASS_MARKER)
    return 0


def main() -> int:
    check = Check()
    print("ENGEL_DEBRUIJN_QUANTUM_BUILD_PROMOTE_GRAPH_ALIGNMENT_CONTRACT_VERIFIER")
    print(f"ROOT {ROOT}")
    print("Mode: contract validation only; no runtime/apply/build execution, no routes, no PyInstaller, no live/dist/build/backups writes, no provider/model/network calls, no mutations")

    if ROOT.resolve(strict=False) != Path(WORKSPACE_TEXT).resolve(strict=False):
        check.fail(f"verifier must run inside {WORKSPACE_TEXT}; resolved root is {ROOT}")
        return finish(check)

    data = read_required(check)
    inspect_related(check)
    if data is not None:
        check_identity_and_flags(check, data)
        check_input_and_eligible_state(check, data)
        check_actions_and_gates(check, data)
        check_transaction_receipt_command(check, data)
        check_future_verifier_and_sequence(check, data)
    else:
        check.skip("contract schema checks skipped because required contract files are missing")

    active_source_scan(check)
    return finish(check)


if __name__ == "__main__":
    raise SystemExit(main())
