#!/usr/bin/env python3
from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
WORKSPACE_TEXT = r"D:\b.WorkSpace\Engel App"

CONTRACT_ID = "ENGEL_DEBRUIJN_QUANTUM_APPLY_ENGINE_GRAPH_ALIGNMENT_CONTRACT_V1"
CONTRACT_JSON = ROOT / "memory" / f"{CONTRACT_ID}.json"
CONTRACT_MD = ROOT / "memory" / f"{CONTRACT_ID}.md"
CONTRACT_REPORT = ROOT / "reports" / "codex_bridge" / f"{CONTRACT_ID}.md"

PASS_MARKER = "DEBRUIJN_QUANTUM_APPLY_ENGINE_GRAPH_ALIGNMENT_CONTRACT_VERIFICATION_PASS"
APPROVAL_PHRASE = "APPROVE_DEBRUIJN_QUANTUM_APPLY_VERIFIED_PROPOSAL_V1"

REQUIRED_FILES = [
    CONTRACT_JSON,
    CONTRACT_MD,
    CONTRACT_REPORT,
]

RELATED_FILES = [
    ROOT / "memory" / "ENGEL_DEBRUIJN_GRAPH_SEQUENCE_MODEL_V1.json",
    ROOT / "tools" / "verify_debruijn_graph_sequence_model.py",
    ROOT / "memory" / "ENGEL_DEBRUIJN_QUANTUM_RUNTIME_ENGINE_GRAPH_ALIGNMENT_CONTRACT_V1.json",
    ROOT / "tools" / "verify_debruijn_quantum_runtime_engine_graph_alignment_contract.py",
    ROOT / "engel_debruijn_quantum_runtime.py",
    ROOT / "tools" / "verify_debruijn_quantum_runtime_engine.py",
    ROOT / "memory" / "ENGEL_DEBRUIJN_QUANTUM_APPLY_ENGINE_CONTRACT_V1.json",
    ROOT / "tools" / "verify_debruijn_quantum_apply_engine_contract.py",
    ROOT / "engel_debruijn_quantum_apply.py",
    ROOT / "tools" / "verify_debruijn_quantum_apply_engine.py",
    ROOT / "engel_app.py",
    ROOT / "memory" / "ENGEL_COMMANDS.md",
    ROOT / "memory" / "ROUTE_VERIFICATION_SET_V1.json",
]

FALSE_FLAGS = [
    "apply_graph_alignment_enabled_now",
    "apply_source_changed_now",
    "runtime_source_changed_now",
    "build_promote_changed_now",
    "command_route_added_now",
    "actual_apply_enabled_now",
    "source_mutation_enabled_now",
    "route_mutation_enabled_now",
    "queue_mutation_enabled_now",
    "trusted_memory_write_enabled_now",
    "memory_promotion_enabled_now",
    "provider_api_enabled_now",
    "network_enabled_now",
    "local_llm_inference_enabled_now",
    "background_worker_enabled_now",
    "autorun_enabled_now",
    "build_promote_enabled_now",
    "git_stage_commit_enabled_now",
]

REQUIRED_KEYS = [
    "current_enabled_flags",
    "graph_aligned_apply_input_model",
    "verified_for_apply_edge_state",
    "graph_aligned_allowed_apply_actions",
    "graph_aligned_forbidden_apply_actions",
    "graph_aligned_apply_gates",
    "graph_aligned_transaction_model",
    "graph_aligned_receipt_model",
    "future_command_concept",
    "safety_boundary",
    "future_verifier",
    "future_implementation_sequence",
    "safety_preserved",
    "recommended_next_slice",
]

GRAPH_INPUT_TERMS = [
    "source node state",
    "target node state",
    "edge transition ID",
    "edge label",
    "append operation",
    "overlap preserved",
    "coverage status",
    "measurement status",
    "verifier interference result",
    "receipt/evidence path",
    "human review status",
    "target path list",
    "bounded action list",
]

GRAPH_INPUT_REQUIREMENTS = [
    "inside workspace",
    "structured JSON",
    "approved structured package",
    "generated by approved De Bruijn runtime/proposal system",
    "not executable",
    "not treated as instructions",
    "no external URLs",
    "no path traversal",
    "no arbitrary shell commands",
    "no provider/model/network directives",
    "no trusted-memory promotion directives",
]

VERIFIED_EDGE_FIELDS: dict[str, Any] = {
    "verified_for_apply": True,
    "measurement_status": "verified_for_apply",
    "coverage_status": "approved_for_apply_candidate",
    "apply_scope": "bounded_file_structure",
    "edge_label_present": True,
    "edge_transition_id_present": True,
    "source_node_validated": True,
    "target_node_validated": True,
    "overlap_preserved": True,
    "target_paths_validated": True,
    "unsafe_content_scan_passed": True,
    "authority_hierarchy_passed": True,
    "prompt_injection_guard_passed": True,
    "password_gate_required": True,
    "approval_phrase_required": True,
    "human_review_required": True,
}

ALLOWED_ACTION_TERMS = [
    "create missing contract scaffold file",
    "create missing verifier scaffold file",
    "create missing report scaffold file",
    "update documentation map",
    "update safe project index/checklist docs",
    "update route metadata",
    "route verifier approves",
    "create receipts/reports",
    "create candidate proposal files",
    "update approved backend status docs",
]

ALLOWED_ACTION_REQUIREMENTS = [
    "edge_transition_id",
    "source/target node relationship preserved",
    "overlap with prior approved structure preserved",
    WORKSPACE_TEXT,
    "explicitly listed in proposal",
    "before/after receipt evidence",
    "no overwriting non-empty files unless diff explicitly reviewed",
    "human_review_required true after apply",
    "apply receipt written",
]

FORBIDDEN_TERMS = [
    "applying an edge without an edge label",
    "applying an edge without verifier evidence",
    "silent graph mutation",
    "unlabelled transition",
    "trusting repeated traversal as memory",
    "deleting source files",
    "arbitrary source rewrite",
    "editing trusted memory",
    "promoting memory",
    "installing packages",
    "enabling provider/network/model runtime",
    "enabling local LLM inference",
    "enabling agent autorun",
    "enabling background workers",
    "creating scheduler/startup hooks",
    "build/promote EXEs",
    "git stage/commit/push automation",
    "modifying local password config",
    "exposing password/salt/hash values",
    "running commands from proposal content",
    "executing generated candidate content",
    "expanding outside workspace",
    "writing to live/dist/build/backups",
]

BEFORE_APPLY_GATES = [
    "apply graph alignment contract exists",
    "apply graph alignment verifier passes",
    "graph sequence model verifier passes",
    "runtime graph alignment verifier passes",
    "apply engine verifier passes",
    "apply engine contract verifier passes",
    "runtime engine verifier passes",
    "candidate proposal verifier passes",
    "entanglement verifier passes",
    "backend status consistency verifier passes",
    "untrusted-content verifier passes",
    "De Bruijn import boundary verifier passes",
    "authority hierarchy passes",
    "prompt injection guard passes",
    "Global Password Gate verifier passes",
    "proposal has graph edge label",
    "proposal is verified_for_apply",
    "approval phrase present",
    "password gate runtime check passes, redacted",
    "target paths inside workspace",
    "git staged set clean or intentionally empty",
    "local password config not staged/committed",
    "no unsafe dirty state in target files",
]

AFTER_APPLY_GATES = [
    "apply receipt written",
    "graph edge status moves to applied_review_required, not trusted",
    "post-apply verifier stack passes",
    "changed files match approved edge proposal",
    "coverage status updated only through receipt/report evidence",
    "no generated proposal applied beyond approved edge scope",
    "no trusted-memory write",
    "no route/queue mutation outside approved scope",
    "human_review_required remains true",
    "build/promote remains separate",
]

TRANSACTION_STEPS = [
    "preflight_read",
    "validate_graph_edge_package",
    "validate_source_target_nodes",
    "validate_edge_label",
    "validate_append_operation",
    "validate_overlap_preserved",
    "validate_target_paths",
    "validate_diff_or_scaffold_plan",
    "create_backup_snapshot_or_hash_manifest",
    "apply_bounded_edge_change",
    "write_graph_apply_receipt",
    "run_post_apply_verifiers",
    "classify_result",
]

RECEIPT_FIELDS = [
    "receipt_id",
    "engine_id",
    "action_type",
    "started_at",
    "ended_at",
    "input_proposal_path",
    "proposal_id",
    "proposal_hash",
    "source_node_state_id",
    "target_node_state_id",
    "edge_transition_id",
    "edge_label",
    "append_operation",
    "overlap_preserved",
    "sequence_position",
    "coverage_status_before",
    "coverage_status_after",
    "measurement_status_before",
    "measurement_status_after",
    "verifier_interference_result",
    "approval_detected",
    "approval_phrase_name",
    "password_gate_result",
    "pre_apply_verifier_results",
    "files_read",
    "files_changed",
    "files_not_changed",
    "target_paths_validated",
    "forbidden_actions_not_performed",
    "post_apply_verifier_results",
    "rollback_note",
    "final_status",
    "human_review_required",
]

FUTURE_COMMAND_BOOLS = [
    "requires_exact_approval_phrase",
    "requires_global_password_gate",
    "requires_graph_edge_label",
    "requires_verified_for_apply",
    "proposal_path_must_be_inside_workspace",
    "reject_external_urls",
    "reject_path_traversal",
    "reject_arbitrary_extra_args",
    "reject_output_path_override",
    "reject_shell_commands",
    "reject_provider_model_network_args",
    "fail_closed_on_missing_verifier_or_gate",
]

EXPECTED_SEQUENCE = [
    "ENGEL_DEBRUIJN_QUANTUM_APPLY_ENGINE_GRAPH_ALIGNMENT_CONTRACT_V1",
    "ENGEL_DEBRUIJN_QUANTUM_APPLY_ENGINE_GRAPH_ALIGNMENT_VERIFIER_V1",
    "ENGEL_DEBRUIJN_QUANTUM_APPLY_ENGINE_GRAPH_ALIGNMENT_V1",
    "ENGEL_DEBRUIJN_QUANTUM_APPLY_ENGINE_SOURCE_SMOKE_V2",
    "ENGEL_DEBRUIJN_QUANTUM_APPROVED_APPLY_COMMAND_CONTRACT_V1",
    "ENGEL_DEBRUIJN_QUANTUM_APPROVED_APPLY_COMMAND_VERIFIER_V1",
    "ENGEL_DEBRUIJN_QUANTUM_APPROVED_APPLY_COMMAND_V1",
    "ENGEL_DEBRUIJN_QUANTUM_APPLY_ENGINE_GRAPH_ALIGNMENT_CLOSEOUT_REVIEW_V1",
    "ENGEL_DEBRUIJN_QUANTUM_BUILD_PROMOTE_GRAPH_ALIGNMENT_CONTRACT_V1",
]

EXCLUDED_DIRS = {
    ".git",
    "build",
    "dist",
    "live",
    "backups",
    "__pycache__",
    ".venv",
    "venv",
    "node_modules",
    "reports",
    "code_workspace",
}

SCAN_SUFFIXES = {".py", ".ps1", ".json", ".toml", ".yaml", ".yml", ".bat", ".cmd", ".md"}
ROUTE_METADATA = ROOT / "memory" / "ROUTE_VERIFICATION_SET_V1.json"
COMMAND_DOC = ROOT / "memory" / "ENGEL_COMMANDS.md"
RELEVANT_ACTIVE_FILES = {
    ROOT / "engel_app.py",
    ROOT / "engel_debruijn_quantum_apply.py",
    ROUTE_METADATA,
    COMMAND_DOC,
}

ACTIVE_PATTERNS = [
    ("apply_graph_alignment_enabled_now true", re.compile(r"apply_graph_alignment_enabled_now\s*[:=]\s*true", re.IGNORECASE)),
    ("actual_apply_enabled_now true", re.compile(r"actual_apply_enabled_now\s*[:=]\s*true", re.IGNORECASE)),
    ("command_route_added_now true", re.compile(r"command_route_added_now\s*[:=]\s*true", re.IGNORECASE)),
    ("De Bruijn apply route handler", re.compile(r"engel\s+ai\s+debruijn\s+quantum\s+apply", re.IGNORECASE)),
    ("approval phrase route handler", re.compile(re.escape(APPROVAL_PHRASE), re.IGNORECASE)),
    ("apply verified graph edge", re.compile(r"apply_verified_graph_edge", re.IGNORECASE)),
    ("active bounded edge change function", re.compile(r"def\s+apply_bounded_edge_change\b|apply_bounded_edge_change\s*\(", re.IGNORECASE)),
    ("source mutation true", re.compile(r"source_mutation_enabled_now\s*[:=]\s*true", re.IGNORECASE)),
    ("route mutation true", re.compile(r"route_mutation_enabled_now\s*[:=]\s*true", re.IGNORECASE)),
    ("queue mutation true", re.compile(r"queue_mutation_enabled_now\s*[:=]\s*true", re.IGNORECASE)),
    ("trusted memory write true", re.compile(r"trusted_memory_write_enabled_now\s*[:=]\s*true", re.IGNORECASE)),
    ("memory promotion true", re.compile(r"memory_promotion_enabled_now\s*[:=]\s*true", re.IGNORECASE)),
    ("provider api true", re.compile(r"provider_api_enabled_now\s*[:=]\s*true", re.IGNORECASE)),
    ("network true", re.compile(r"network_enabled_now\s*[:=]\s*true", re.IGNORECASE)),
    ("local llm true", re.compile(r"local_llm_inference_enabled_now\s*[:=]\s*true", re.IGNORECASE)),
    ("background worker true", re.compile(r"background_worker_enabled_now\s*[:=]\s*true", re.IGNORECASE)),
    ("autorun true", re.compile(r"autorun_enabled_now\s*[:=]\s*true", re.IGNORECASE)),
    ("git stage commit true", re.compile(r"git_stage_commit_enabled_now\s*[:=]\s*true", re.IGNORECASE)),
    ("auto apply", re.compile(r"auto[_\s-]*apply", re.IGNORECASE)),
    ("auto build", re.compile(r"auto[_\s-]*build", re.IGNORECASE)),
    ("auto promote", re.compile(r"auto[_\s-]*promote", re.IGNORECASE)),
    ("execute proposal", re.compile(r"execute[_\s-]+proposal", re.IGNORECASE)),
    ("trust proposal", re.compile(r"trust[_\s-]+proposal", re.IGNORECASE)),
    ("promote proposal", re.compile(r"promote[_\s-]+proposal", re.IGNORECASE)),
    ("subprocess apply", re.compile(r"subprocess[^\n]{0,120}apply", re.IGNORECASE)),
    ("git commit", re.compile(r"\bgit\s+commit\b", re.IGNORECASE)),
    ("git add", re.compile(r"\bgit\s+add\b", re.IGNORECASE)),
    ("pyinstaller", re.compile(r"pyinstaller", re.IGNORECASE)),
    ("package install", re.compile(r"\b(pip|uv|poetry|npm)\s+(install|add)\b", re.IGNORECASE)),
]

SAFE_LINE_MARKERS = [
    "forbid",
    "forbidden",
    "must not",
    "do not",
    "never",
    "disabled",
    "future",
    "future-only",
    "contract",
    "contract_only",
    "review_required",
    "verifier",
    "scan",
    "pattern",
    "reject",
    "no ",
    "no_",
    "not implemented",
    "dry-run",
    "dry_run",
    "validate-only",
    "validate only",
    "false",
]


class Check:
    def __init__(self) -> None:
        self.failures: list[str] = []
        self.review_required: list[str] = []

    def line(self, level: str, message: str) -> None:
        safe_message = message.encode("ascii", "backslashreplace").decode("ascii")
        print(f"{level} {safe_message}", flush=True)

    def pass_(self, message: str) -> None:
        self.line("PASS", message)

    def fail(self, message: str) -> None:
        self.failures.append(message)
        self.line("FAIL", message)

    def info(self, message: str) -> None:
        self.line("INFO", message)

    def skip(self, message: str) -> None:
        self.line("SKIP", message)

    def review(self, message: str) -> None:
        self.review_required.append(message)
        self.line("REVIEW_REQUIRED", message)


def rel(path: Path) -> str:
    try:
        return str(path.resolve(strict=False).relative_to(ROOT.resolve(strict=False))).replace("/", "\\")
    except ValueError:
        return str(path)


def normalize(value: Any) -> str:
    text = value if isinstance(value, str) else json.dumps(value, sort_keys=True, ensure_ascii=True)
    text = text.lower().replace("\\", " ")
    text = re.sub(r"[^a-z0-9_]+", " ", text)
    return re.sub(r"\s+", " ", text).strip()


def has_term(blob: str, term: str) -> bool:
    return normalize(term) in blob


def require_terms(check: Check, label: str, value: Any, terms: list[str]) -> None:
    blob = normalize(value)
    missing = [term for term in terms if not has_term(blob, term)]
    if missing:
        check.fail(f"{label} missing required terms: {', '.join(missing)}")
    else:
        check.pass_(f"{label} contains required terms")


def read_required(check: Check) -> dict[str, Any] | None:
    missing = [path for path in REQUIRED_FILES if not path.exists()]
    if missing:
        for path in missing:
            check.fail(f"required apply graph-alignment contract file missing: {rel(path)}")
        return None
    for path in REQUIRED_FILES:
        check.pass_(f"required apply graph-alignment contract file exists: {rel(path)}")
    try:
        data = json.loads(CONTRACT_JSON.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        check.fail(f"contract JSON is invalid: {exc}")
        return None
    if not isinstance(data, dict):
        check.fail("contract JSON top-level value must be an object")
        return None
    check.pass_("contract JSON parsed")
    return data


def inspect_related(check: Check) -> None:
    for path in RELATED_FILES:
        if path.exists():
            check.info(f"related file present for context: {rel(path)}")
        else:
            check.skip(f"related file not present: {rel(path)}")


def check_identity_and_flags(check: Check, data: dict[str, Any]) -> None:
    expected = {
        "contract_id": CONTRACT_ID,
        "status": "contract_only",
        "active_workspace": WORKSPACE_TEXT,
        "aligns_apply_engine": "debruijn_quantum_apply_engine",
        "source_model_contract": "ENGEL_DEBRUIJN_GRAPH_SEQUENCE_MODEL_V1",
        "runtime_graph_alignment_dependency": "ENGEL_DEBRUIJN_QUANTUM_RUNTIME_ENGINE_GRAPH_ALIGNMENT_CONTRACT_V1",
    }
    for key, value in expected.items():
        if data.get(key) == value:
            check.pass_(f"{key} matches expected value")
        else:
            check.fail(f"{key} expected {value!r}, got {data.get(key)!r}")

    missing = [key for key in REQUIRED_KEYS if key not in data]
    if missing:
        check.fail(f"contract JSON missing required keys: {', '.join(missing)}")
    else:
        check.pass_("contract JSON includes all required top-level keys")

    current_flags = data.get("current_enabled_flags")
    if not isinstance(current_flags, dict):
        check.fail("current_enabled_flags must be an object")
        current_flags = {}
    for flag in FALSE_FLAGS:
        nested = current_flags.get(flag)
        top = data.get(flag)
        if nested is False or top is False:
            check.pass_(f"{flag} is false")
        else:
            check.fail(f"{flag} must be false in current_enabled_flags or top-level contract")


def check_graph_input_model(check: Check, data: dict[str, Any]) -> None:
    model = data.get("graph_aligned_apply_input_model")
    require_terms(check, "graph_aligned_apply_input_model required package fields", model, GRAPH_INPUT_TERMS)
    require_terms(check, "graph_aligned_apply_input_model requirements", model, GRAPH_INPUT_REQUIREMENTS)


def check_verified_edge_state(check: Check, data: dict[str, Any]) -> None:
    state = data.get("verified_for_apply_edge_state")
    if not isinstance(state, dict):
        check.fail("verified_for_apply_edge_state must be an object")
        return
    required = state.get("required_fields", state)
    if not isinstance(required, dict):
        check.fail("verified_for_apply_edge_state.required_fields must be an object")
        return
    for key, expected in VERIFIED_EDGE_FIELDS.items():
        if required.get(key) == expected:
            check.pass_(f"verified_for_apply_edge_state requires {key} == {expected!r}")
        else:
            check.fail(f"verified_for_apply_edge_state {key} expected {expected!r}, got {required.get(key)!r}")
    require_terms(
        check,
        "verified_for_apply_edge_state meaning",
        state,
        [
            "verified_for_apply is still not trusted status",
            "eligible for a password-gated apply attempt",
        ],
    )


def check_actions_and_gates(check: Check, data: dict[str, Any]) -> None:
    allowed = data.get("graph_aligned_allowed_apply_actions")
    require_terms(check, "graph_aligned_allowed_apply_actions allowed set", allowed, ALLOWED_ACTION_TERMS)
    require_terms(check, "graph_aligned_allowed_apply_actions requirements", allowed, ALLOWED_ACTION_REQUIREMENTS)

    forbidden = data.get("graph_aligned_forbidden_apply_actions")
    require_terms(check, "graph_aligned_forbidden_apply_actions", forbidden, FORBIDDEN_TERMS)
    require_terms(check, "safety_boundary forbidden behavior", data.get("safety_boundary"), FORBIDDEN_TERMS)

    gates = data.get("graph_aligned_apply_gates")
    before = gates.get("before_apply") if isinstance(gates, dict) else gates
    after = gates.get("after_apply") if isinstance(gates, dict) else gates
    require_terms(check, "graph_aligned_apply_gates before_apply", before, BEFORE_APPLY_GATES)
    require_terms(check, "graph_aligned_apply_gates after_apply", after, AFTER_APPLY_GATES)


def check_transaction_receipt_command(check: Check, data: dict[str, Any]) -> None:
    transaction = data.get("graph_aligned_transaction_model")
    require_terms(check, "graph_aligned_transaction_model steps", transaction, TRANSACTION_STEPS)
    require_terms(
        check,
        "graph_aligned_transaction_model rollback rules",
        transaction,
        [
            "V1 does not auto-rollback",
            "rollback notes",
            "hash manifests",
            "APPLIED_REVIEW_REQUIRED",
            "evidence/backups are not deleted",
        ],
    )

    receipt = data.get("graph_aligned_receipt_model")
    require_terms(check, "graph_aligned_receipt_model folder", receipt, ["reports\\debruijn_quantum_apply_receipts\\"])
    require_terms(check, "graph_aligned_receipt_model fields", receipt, RECEIPT_FIELDS)
    require_terms(check, "graph_aligned_receipt_model secret exclusion", receipt, ["no password/salt/hash values in receipt"])

    command = data.get("future_command_concept")
    expected_command = (
        "engel ai debruijn quantum apply "
        "APPROVE_DEBRUIJN_QUANTUM_APPLY_VERIFIED_PROPOSAL_V1 proposal=<proposal_path>"
    )
    if isinstance(command, dict) and command.get("command") == expected_command:
        check.pass_("future_command_concept command matches expected future command")
    elif isinstance(command, str) and expected_command in command:
        check.pass_("future_command_concept command text contains expected future command")
    else:
        check.fail("future_command_concept missing expected future command")
    require_terms(check, "future_command_concept requirements", command, FUTURE_COMMAND_BOOLS)
    require_terms(check, "future_command_concept future-only boundary", command, ["command is future-only", "no route added now"])


def check_future_verifier_and_sequence(check: Check, data: dict[str, Any]) -> None:
    future_verifier = data.get("future_verifier")
    require_terms(
        check,
        "future_verifier",
        future_verifier,
        [
            "tools\\verify_debruijn_quantum_apply_engine_graph_alignment_contract.py",
            "contract exists",
            "apply graph alignment disabled",
            "actual apply disabled",
            "no route added",
            "graph edge label",
            "receipt model",
            "active source scan",
        ],
    )

    sequence = data.get("future_implementation_sequence")
    if not isinstance(sequence, list):
        check.fail("future_implementation_sequence must be a list")
        return
    missing = [item for item in EXPECTED_SEQUENCE if item not in sequence]
    if missing:
        check.fail(f"future_implementation_sequence missing: {', '.join(missing)}")
        return
    positions = [sequence.index(item) for item in EXPECTED_SEQUENCE]
    if positions == sorted(positions):
        check.pass_("future_implementation_sequence contains required ordered slices")
    else:
        check.fail("future_implementation_sequence contains required entries out of order")

    if data.get("recommended_next_slice") == "ENGEL_DEBRUIJN_QUANTUM_APPLY_ENGINE_GRAPH_ALIGNMENT_VERIFIER_V1":
        check.pass_("recommended_next_slice points to apply graph-alignment verifier")
    else:
        check.fail("recommended_next_slice must be ENGEL_DEBRUIJN_QUANTUM_APPLY_ENGINE_GRAPH_ALIGNMENT_VERIFIER_V1")


def should_scan(path: Path) -> bool:
    resolved = path.resolve(strict=False)
    try:
        parts = resolved.relative_to(ROOT.resolve(strict=False)).parts
    except ValueError:
        return False
    if any(part in EXCLUDED_DIRS for part in parts):
        return False
    if path == Path(__file__).resolve():
        return False
    if len(parts) >= 2 and parts[0] == "tools" and path.name.startswith("verify_"):
        return False
    if path.suffix.lower() not in SCAN_SUFFIXES:
        return False
    return any(resolved == candidate.resolve(strict=False) for candidate in RELEVANT_ACTIVE_FILES)


def safe_line(line: str) -> bool:
    lower = line.lower()
    return any(marker in lower for marker in SAFE_LINE_MARKERS)


def active_source_scan(check: Check) -> None:
    findings: list[str] = []
    scanned = 0
    for path in sorted(RELEVANT_ACTIVE_FILES, key=lambda item: rel(item)):
        if not path.exists() or not should_scan(path):
            continue
        scanned += 1
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")
        except OSError as exc:
            check.review(f"could not read active source file {rel(path)}: {exc}")
            continue
        for lineno, line in enumerate(text.splitlines(), start=1):
            if safe_line(line):
                continue
            for label, pattern in ACTIVE_PATTERNS:
                if pattern.search(line):
                    lower = line.lower()
                    is_route_surface = path.name == "engel_app.py" or path.resolve(strict=False) in {
                        ROUTE_METADATA.resolve(strict=False),
                        COMMAND_DOC.resolve(strict=False),
                    }
                    if label in {"De Bruijn apply route handler", "approval phrase route handler"} and not is_route_surface:
                        continue
                    if label in {
                        "pyinstaller",
                        "package install",
                        "git commit",
                        "git add",
                        "auto apply",
                        "auto build",
                        "auto promote",
                        "execute proposal",
                        "trust proposal",
                        "promote proposal",
                        "subprocess apply",
                    } and not ("debruijn" in lower and ("apply" in lower or "graph" in lower)):
                        continue
                    findings.append(f"{rel(path)}:{lineno}: {label}: {line.strip()[:160]}")

    check.info(f"active source scan inspected {scanned} source/config files")
    if findings:
        for finding in findings:
            check.review(f"possible active apply graph-alignment behavior: {finding}")
        check.fail("active source scan found possible active apply graph-alignment behavior")
    else:
        check.pass_("active source scan found no active apply graph-alignment behavior")


def finish(check: Check) -> int:
    if check.review_required and not check.failures:
        check.info(f"review-required notes emitted: {len(check.review_required)}")
    if check.failures:
        check.info(f"verification failed with {len(check.failures)} failure(s)")
        return 1
    print(PASS_MARKER)
    return 0


def main() -> int:
    check = Check()
    print("ENGEL_DEBRUIJN_QUANTUM_APPLY_ENGINE_GRAPH_ALIGNMENT_CONTRACT_VERIFIER")
    print(f"ROOT {ROOT}")
    print("Mode: contract validation only; no runtime/apply/build execution, no routes, no provider/model/network calls, no mutations")

    if ROOT.resolve(strict=False) != Path(WORKSPACE_TEXT).resolve(strict=False):
        check.fail(f"verifier must run inside {WORKSPACE_TEXT}; resolved root is {ROOT}")
        return finish(check)

    data = read_required(check)
    inspect_related(check)
    if data is not None:
        check_identity_and_flags(check, data)
        check_graph_input_model(check, data)
        check_verified_edge_state(check, data)
        check_actions_and_gates(check, data)
        check_transaction_receipt_command(check, data)
        check_future_verifier_and_sequence(check, data)
    else:
        check.skip("contract schema checks skipped because required contract files are missing")

    active_source_scan(check)
    return finish(check)


if __name__ == "__main__":
    raise SystemExit(main())
